### ISSUE TITLE
Hot-loading dependencies sample doesn't work in lein

### ISSUE THREAD

**Issue by jc776** [nrepl/nrepl#113]
## Expected behavior
The pomegranate [hot-loading dependencies](https://nrepl.org/nrepl/usage/misc.html) sample (for `clj`) should also work in `lein`.

## Actual behavior
The dependency gets added without error to some classloader, but isn't available to `require`. It's visible as a resource.
```
PS C:\Users\Jack\SSD\Projects\classloaders-201> lein run -m nrepl.cmdline --interactive
nREPL server started on port 53374 on host 127.0.0.1 - nrepl://127.0.0.1:53374
nREPL 0.5.3
Clojure 1.10.0
Java HotSpot(TM) 64-Bit Server VM 10.0.1+10
Interrupt: Control+C
Exit:      Control+D or (exit) or (quit)
user=> (require 'bidi.bidi)
Execution error (FileNotFoundException) at user/eval1282 (form-init11955807739262716208.clj:1).
Could not locate bidi/bidi__init.class, bidi/bidi.clj or bidi/bidi.cljc on classpath.
user=> (require '[cemerick.pomegranate :as pg])
nil
user=> (pg/add-dependencies :coordinates '[[bidi "2.1.5"]]
                     :repositories (merge cemerick.pomegranate.aether/maven-central {"clojars" "https://clojars.org/repo"}))
{[bidi "2.1.5"] #{[prismatic/schema "1.1.7" :exclusions [[org.clojure/tools.reader]]]}, [prismatic/schema "1.1.7" :exclusions [[org.clojure/tools.reader]]] nil}
user=> (require 'bidi.bidi)
Execution error (FileNotFoundException) at user/eval1756 (form-init11955807739262716208.clj:1).
Could not locate bidi/bidi__init.class, bidi/bidi.clj or bidi/bidi.cljc on classpath.
user=> (.getResource (.getContextClassLoader (Thread/currentThread)) "bidi/bidi.cljc")
#object[java.net.URL 0x93a1078 "jar:file:/C:/Users/Jack/.m2/repository/bidi/bidi/2.1.5/bidi-2.1.5.jar!/bidi/bidi.cljc"]
user=>
```

## Steps to reproduce the problem
Example project: https://github.com/jc776/classloaders-201, then follow REPL session above
It is possible to get the dependency to load by bringing back some additional behaviour that was in cemerick/pomegranate#102 but never merged, which was closed in favour of nrepl/nrepl#35 - see project's README.

## Environment & Version information
- lein 2.8.3, nREPL 0.5.3
- Clojure 1.10.0
- (Oracle) Java 10
- Windows 10

**Comment by SevereOverfl0w** [comment]
I have confirmed that the memoize example works for `clj` under java 11.

**Comment by SevereOverfl0w** [comment]
Sorry, I cannot reproduce with Lein either:

```
root@bianca2:/bin# lein run -m nrepl.cmdline --interactive
Retrieving clojure-complete/clojure-complete/0.2.5/clojure-complete-0.2.5.pom from clojars
Retrieving clojure-complete/clojure-complete/0.2.5/clojure-complete-0.2.5.jar from clojars
nREPL server started on port 43365 on host localhost - nrepl://localhost:43365
nREPL 0.5.3
Clojure 1.8.0
OpenJDK 64-Bit Server VM 11.0.1+13-Debian-2bpo91
Interrupt: Control+C
Exit:      Control+D or (exit) or (quit)
user=> (require '[cemerick.pomegranate :as pg])
nil
user=> (pg/add-dependencies :coordinates '[[bidi "2.1.5"]]
                     :repositories (merge cemerick.pomegranate.aether/maven-central {"clojars" "https://clojars.org/repo"}))
{[bidi "2.1.5"] #{[prismatic/schema "1.1.7" :exclusions [[org.clojure/tools.reader]]]}, [prismatic/schema "1.1.7" :exclusions [[org.clojure/tools.reader]]] nil}
user=> (require 'bidi.bidi)
nil
```

The only difference I see is Windows vs Linux. But I don't see how that could break things.

**Comment by bbatsov** [comment]
What about simply running `lein repl`? Perhaps it’s something related to REPL-y?

**Comment by SevereOverfl0w** [comment]
The repro in Op uses lein run though, but worth  checking

**Comment by jc776** [comment]
If I run the commands in `lein run -m` in an empty folder, it's using Clojure 1.8.0 and does work for both libraries. I'm not sure what version of pomegranate is being used here - `lein deps :tree` says "Couldn't find project.clj, which is needed for deps".
```
PS D:\Projects\done\xxx> lein run -m nrepl.cmdline --interactive
nREPL server started on port 55598 on host 127.0.0.1 - nrepl://127.0.0.1:55598
nREPL 0.5.3
Clojure 1.8.0
Java HotSpot(TM) 64-Bit Server VM 10.0.1+10
Interrupt: Control+C
Exit:      Control+D or (exit) or (quit)
user=> (require 'clojure.core.memoize)
FileNotFoundException Could not locate clojure/core/memoize__init.class or clojure/core/memoize.clj on classpath.  clojure.lang.RT.load (RT.java:456)
user=> (require '[cemerick.pomegranate :refer [add-dependencies]])
nil
user=> (add-dependencies :coordinates '[[org.clojure/core.memoize "0.7.1"]]
                         :repositories (merge cemerick.pomegranate.aether/maven-central
                                             {"clojars" "https://clojars.org/repo"}))
{[org.clojure/core.memoize "0.7.1"] #{[org.clojure/core.cache "0.7.1"] [org.clojure/clojure "1.6.0"]}, [org.clojure/core.cache "0.7.1"] #{[org.clojure/data.priority-map "0.0.7"]}, [org.clojure/data.priority-map "0.0.7"] nil, [org.clojure/clojure "1.6.0"] nil}
user=> (add-dependencies :coordinates '[[bidi "2.1.5"]]
                     :repositories (merge cemerick.pomegranate.aether/maven-central {"clojars" "https://clojars.org/repo"}))
{[bidi "2.1.5"] #{[prismatic/schema "1.1.7" :exclusions [[org.clojure/tools.reader]]]}, [prismatic/schema "1.1.7" :exclusions [[org.clojure/tools.reader]]] nil}
user=> (require 'clojure.core.memoize)
nil
user=> (require 'bidi.bidi)
nil
user=>
```

If I use `lein run -m` in the example project in the top post, it's using Clojure 1.10 and fails as before:
```
PS D:\Projects\done\classloaders-201> lein run -m nrepl.cmdline --interactive
nREPL server started on port 55603 on host 127.0.0.1 - nrepl://127.0.0.1:55603
nREPL 0.5.3
Clojure 1.10.0
Java HotSpot(TM) 64-Bit Server VM 10.0.1+10
Interrupt: Control+C
Exit:      Control+D or (exit) or (quit)
user=> (require 'clojure.core.memoize)
Execution error (FileNotFoundException) at user/eval1282 (form-init1289300204722915767.clj:1).
Could not locate clojure/core/memoize__init.class, clojure/core/memoize.clj or clojure/core/memoize.cljc on classpath.
user=> (require '[cemerick.pomegranate :refer [add-dependencies]])
nil
user=> (add-dependencies :coordinates '[[org.clojure/core.memoize "0.7.1"]]
                         :repositories (merge cemerick.pomegranate.aether/maven-central
                                             {"clojars" "https://clojars.org/repo"}))
{[org.clojure/core.memoize "0.7.1"] #{[org.clojure/core.cache "0.7.1"] [org.clojure/clojure "1.6.0"]}, [org.clojure/core.cache "0.7.1"] #{[org.clojure/data.priority-map "0.0.7"]}, [org.clojure/data.priority-map "0.0.7"] nil, [org.clojure/clojure "1.6.0"] nil}
user=> (add-dependencies :coordinates '[[bidi "2.1.5"]]
                     :repositories (merge cemerick.pomegranate.aether/maven-central {"clojars" "https://clojars.org/repo"}))
{[bidi "2.1.5"] #{[prismatic/schema "1.1.7" :exclusions [[org.clojure/tools.reader]]]}, [prismatic/schema "1.1.7" :exclusions [[org.clojure/tools.reader]]] nil}
user=> (require 'clojure.core.memoize)
Execution error (FileNotFoundException) at user/eval1758 (form-init1289300204722915767.clj:1).
Could not locate clojure/core/memoize__init.class, clojure/core/memoize.clj or clojure/core/memoize.cljc on classpath.
user=> (require 'bidi.bidi)
Execution error (FileNotFoundException) at user/eval1760 (form-init1289300204722915767.clj:1).
Could not locate bidi/bidi__init.class, bidi/bidi.clj or bidi/bidi.cljc on classpath.
user=>
```
Fails in the same project using `lein repl`:
```
PS D:\Projects\done\classloaders-201> lein repl
nREPL server started on port 55608 on host 127.0.0.1 - nrepl://127.0.0.1:55608
REPL-y 0.4.3, nREPL 0.5.3
Clojure 1.10.0
Java HotSpot(TM) 64-Bit Server VM 10.0.1+10
    Docs: (doc function-name-here)
          (find-doc "part-of-name-here")
  Source: (source function-name-here)
 Javadoc: (javadoc java-object-or-class-here)
    Exit: Control+D or (exit) or (quit)
 Results: Stored in vars *1, *2, *3, an exception in *e

user=> (require 'clojure.core.memoize)

Execution error (FileNotFoundException) at user/eval1492 (form-init17576427933172615853.clj:1).
Could not locate clojure/core/memoize__init.class, clojure/core/memoize.clj or clojure/core/memoize.cljc on classpath.
user=> (require '[cemerick.pomegranate :refer [add-dependencies]])
nil
user=> (add-dependencies :coordinates '[[org.clojure/core.memoize "0.7.1"]]
  #_=>                          :repositories (merge cemerick.pomegranate.aether/maven-central
))#_=>                                              {"clojars" "https://clojars.org/repo"}{[org.clojure/core.memoize "0.7.1"] #{[org.clojure/core.cache "0.7.1"] [org.clojure/clojure "1.6.0"]}, [org.clojure/core.cache "0.7.1"] #{[org.clojure/data.priority-map "0.0.7"]}, [org.clojure/data.priority-map "0.0.7"] nil, [org.clojure/clojure "1.6.0"] nil}
user=> (add-dependencies :coordinates '[[bidi "2.1.5"]]
  #_=>                      :repositories (merge cemerick.pomegranate.aether/maven-central {"clojars" "https://clojars.org/repo"}))
{[bidi "2.1.5"] #{[prismatic/schema "1.1.7" :exclusions [[org.clojure/tools.reader]]]}, [prismatic/schema "1.1.7" :exclusions [[org.clojure/tools.reader]]] nil}
user=> (require 'clojure.core.memoize)

Execution error (FileNotFoundException) at user/eval1968 (form-init17576427933172615853.clj:1).
Could not locate clojure/core/memoize__init.class, clojure/core/memoize.clj or clojure/core/memoize.cljc on classpath.
user=> (require 'bidi.bidi)

Execution error (FileNotFoundException) at user/eval1970 (form-init17576427933172615853.clj:1).
Could not locate bidi/bidi__init.class, bidi/bidi.clj or bidi/bidi.cljc on classpath.
user=>
```
Succeeds in the empty folder with `lein repl`:
```
nREPL server started on port 55617 on host 127.0.0.1 - nrepl://127.0.0.1:55617
REPL-y 0.4.3, nREPL 0.5.3
Clojure 1.8.0
Java HotSpot(TM) 64-Bit Server VM 10.0.1+10
    Docs: (doc function-name-here)
          (find-doc "part-of-name-here")
  Source: (source function-name-here)
 Javadoc: (javadoc java-object-or-class-here)
    Exit: Control+D or (exit) or (quit)
 Results: Stored in vars *1, *2, *3, an exception in *e

user=> (require 'clojure.core.memoize)
FileNotFoundException Could not locate clojure/core/memoize__init.class or clojure/core/memoize.clj on classpath.  clojure.lang.RT.load (RT.java:456)

user=> (require '[cemerick.pomegranate :refer [add-dependencies]])
nil
user=> (add-dependencies :coordinates '[[org.clojure/core.memoize "0.7.1"]]
  #_=>                          :repositories (merge cemerick.pomegranate.aether/maven-central
))#_=>                                              {"clojars" "https://clojars.org/repo"}{[org.clojure/core.memoize "0.7.1"] #{[org.clojure/core.cache "0.7.1"] [org.clojure/clojure "1.6.0"]}, [org.clojure/core.cache "0.7.1"] #{[org.clojure/data.priority-map "0.0.7"]}, [org.clojure/data.priority-map "0.0.7"] nil, [org.clojure/clojure "1.6.0"] nil}
user=> (add-dependencies :coordinates '[[bidi "2.1.5"]]
  #_=>                      :repositories (merge cemerick.pomegranate.aether/maven-central {"clojars" "https://clojars.org/repo"}))
{[bidi "2.1.5"] #{[prismatic/schema "1.1.7" :exclusions [[org.clojure/tools.reader]]]}, [prismatic/schema "1.1.7" :exclusions [[org.clojure/tools.reader]]] nil}
user=> (require 'clojure.core.memoize)
nil
user=> (require 'bidi.bidi)
nil
user=>
```

**Comment by SevereOverfl0w** [comment]
Admittedly I didn't try the example repo, I thought this would be independent. Okay. Will try look today. 

On January 26, 2019 7:53:54 PM GMT, Jack Coady <notifications@github.com> wrote:
>If I run the commands in `lein run -m` in an empty folder, it's using
>Clojure 1.8.0 and does work for both libraries. I'm not sure what
>version of pomegranate is being used here - `lein deps :tree` says
>"Couldn't find project.clj, which is needed for deps".
>```
>PS D:\Projects\done\xxx> lein run -m nrepl.cmdline --interactive
>nREPL server started on port 55598 on host 127.0.0.1 -
>nrepl://127.0.0.1:55598
>nREPL 0.5.3
>Clojure 1.8.0
>Java HotSpot(TM) 64-Bit Server VM 10.0.1+10
>Interrupt: Control+C
>Exit:      Control+D or (exit) or (quit)
>user=> (require 'clojure.core.memoize)
>FileNotFoundException Could not locate clojure/core/memoize__init.class
>or clojure/core/memoize.clj on classpath.  clojure.lang.RT.load
>(RT.java:456)
>user=> (require '[cemerick.pomegranate :refer [add-dependencies]])
>nil
>user=> (add-dependencies :coordinates '[[org.clojure/core.memoize
>"0.7.1"]]
>         :repositories (merge cemerick.pomegranate.aether/maven-central
>                               {"clojars" "https://clojars.org/repo"}))
>{[org.clojure/core.memoize "0.7.1"] #{[org.clojure/core.cache "0.7.1"]
>[org.clojure/clojure "1.6.0"]}, [org.clojure/core.cache "0.7.1"]
>#{[org.clojure/data.priority-map "0.0.7"]},
>[org.clojure/data.priority-map "0.0.7"] nil, [org.clojure/clojure
>"1.6.0"] nil}
>user=> (add-dependencies :coordinates '[[bidi "2.1.5"]]
>:repositories (merge cemerick.pomegranate.aether/maven-central
>{"clojars" "https://clojars.org/repo"}))
>{[bidi "2.1.5"] #{[prismatic/schema "1.1.7" :exclusions
>[[org.clojure/tools.reader]]]}, [prismatic/schema "1.1.7" :exclusions
>[[org.clojure/tools.reader]]] nil}
>user=> (require 'clojure.core.memoize)
>nil
>user=> (require 'bidi.bidi)
>nil
>user=>
>```
>
>If I use `lein run -m` in the example project in the top post, it's
>using Clojure 1.10 and fails as before:
>```
>PS D:\Projects\done\classloaders-201> lein run -m nrepl.cmdline
>--interactive
>nREPL server started on port 55603 on host 127.0.0.1 -
>nrepl://127.0.0.1:55603
>nREPL 0.5.3
>Clojure 1.10.0
>Java HotSpot(TM) 64-Bit Server VM 10.0.1+10
>Interrupt: Control+C
>Exit:      Control+D or (exit) or (quit)
>user=> (require 'clojure.core.memoize)
>Execution error (FileNotFoundException) at user/eval1282
>(form-init1289300204722915767.clj:1).
>Could not locate clojure/core/memoize__init.class,
>clojure/core/memoize.clj or clojure/core/memoize.cljc on classpath.
>user=> (require '[cemerick.pomegranate :refer [add-dependencies]])
>nil
>user=> (add-dependencies :coordinates '[[org.clojure/core.memoize
>"0.7.1"]]
>         :repositories (merge cemerick.pomegranate.aether/maven-central
>                               {"clojars" "https://clojars.org/repo"}))
>{[org.clojure/core.memoize "0.7.1"] #{[org.clojure/core.cache "0.7.1"]
>[org.clojure/clojure "1.6.0"]}, [org.clojure/core.cache "0.7.1"]
>#{[org.clojure/data.priority-map "0.0.7"]},
>[org.clojure/data.priority-map "0.0.7"] nil, [org.clojure/clojure
>"1.6.0"] nil}
>user=> (add-dependencies :coordinates '[[bidi "2.1.5"]]
>:repositories (merge cemerick.pomegranate.aether/maven-central
>{"clojars" "https://clojars.org/repo"}))
>{[bidi "2.1.5"] #{[prismatic/schema "1.1.7" :exclusions
>[[org.clojure/tools.reader]]]}, [prismatic/schema "1.1.7" :exclusions
>[[org.clojure/tools.reader]]] nil}
>user=> (require 'clojure.core.memoize)
>Execution error (FileNotFoundException) at user/eval1758
>(form-init1289300204722915767.clj:1).
>Could not locate clojure/core/memoize__init.class,
>clojure/core/memoize.clj or clojure/core/memoize.cljc on classpath.
>user=> (require 'bidi.bidi)
>Execution error (FileNotFoundException) at user/eval1760
>(form-init1289300204722915767.clj:1).
>Could not locate bidi/bidi__init.class, bidi/bidi.clj or bidi/bidi.cljc
>on classpath.
>user=>
>```
>Fails in the same project using `lein repl`:
>```
>PS D:\Projects\done\classloaders-201> lein repl
>nREPL server started on port 55608 on host 127.0.0.1 -
>nrepl://127.0.0.1:55608
>REPL-y 0.4.3, nREPL 0.5.3
>Clojure 1.10.0
>Java HotSpot(TM) 64-Bit Server VM 10.0.1+10
>    Docs: (doc function-name-here)
>          (find-doc "part-of-name-here")
>  Source: (source function-name-here)
> Javadoc: (javadoc java-object-or-class-here)
>    Exit: Control+D or (exit) or (quit)
> Results: Stored in vars *1, *2, *3, an exception in *e
>
>user=> (require 'clojure.core.memoize)
>
>Execution error (FileNotFoundException) at user/eval1492
>(form-init17576427933172615853.clj:1).
>Could not locate clojure/core/memoize__init.class,
>clojure/core/memoize.clj or clojure/core/memoize.cljc on classpath.
>user=> (require '[cemerick.pomegranate :refer [add-dependencies]])
>nil
>user=> (add-dependencies :coordinates '[[org.clojure/core.memoize
>"0.7.1"]]
>#_=>                          :repositories (merge
>cemerick.pomegranate.aether/maven-central
>))#_=>                                              {"clojars"
>"https://clojars.org/repo"}{[org.clojure/core.memoize "0.7.1"]
>#{[org.clojure/core.cache "0.7.1"] [org.clojure/clojure "1.6.0"]},
>[org.clojure/core.cache "0.7.1"] #{[org.clojure/data.priority-map
>"0.0.7"]}, [org.clojure/data.priority-map "0.0.7"] nil,
>[org.clojure/clojure "1.6.0"] nil}
>user=> (add-dependencies :coordinates '[[bidi "2.1.5"]]
>#_=>                      :repositories (merge
>cemerick.pomegranate.aether/maven-central {"clojars"
>"https://clojars.org/repo"}))
>{[bidi "2.1.5"] #{[prismatic/schema "1.1.7" :exclusions
>[[org.clojure/tools.reader]]]}, [prismatic/schema "1.1.7" :exclusions
>[[org.clojure/tools.reader]]] nil}
>user=> (require 'clojure.core.memoize)
>
>Execution error (FileNotFoundException) at user/eval1968
>(form-init17576427933172615853.clj:1).
>Could not locate clojure/core/memoize__init.class,
>clojure/core/memoize.clj or clojure/core/memoize.cljc on classpath.
>user=> (require 'bidi.bidi)
>
>Execution error (FileNotFoundException) at user/eval1970
>(form-init17576427933172615853.clj:1).
>Could not locate bidi/bidi__init.class, bidi/bidi.clj or bidi/bidi.cljc
>on classpath.
>user=>
>```
>Succeeds in the empty folder with `lein repl`:
>```
>nREPL server started on port 55617 on host 127.0.0.1 -
>nrepl://127.0.0.1:55617
>REPL-y 0.4.3, nREPL 0.5.3
>Clojure 1.8.0
>Java HotSpot(TM) 64-Bit Server VM 10.0.1+10
>    Docs: (doc function-name-here)
>          (find-doc "part-of-name-here")
>  Source: (source function-name-here)
> Javadoc: (javadoc java-object-or-class-here)
>    Exit: Control+D or (exit) or (quit)
> Results: Stored in vars *1, *2, *3, an exception in *e
>
>user=> (require 'clojure.core.memoize)
>FileNotFoundException Could not locate clojure/core/memoize__init.class
>or clojure/core/memoize.clj on classpath.  clojure.lang.RT.load
>(RT.java:456)
>
>user=> (require '[cemerick.pomegranate :refer [add-dependencies]])
>nil
>user=> (add-dependencies :coordinates '[[org.clojure/core.memoize
>"0.7.1"]]
>#_=>                          :repositories (merge
>cemerick.pomegranate.aether/maven-central
>))#_=>                                              {"clojars"
>"https://clojars.org/repo"}{[org.clojure/core.memoize "0.7.1"]
>#{[org.clojure/core.cache "0.7.1"] [org.clojure/clojure "1.6.0"]},
>[org.clojure/core.cache "0.7.1"] #{[org.clojure/data.priority-map
>"0.0.7"]}, [org.clojure/data.priority-map "0.0.7"] nil,
>[org.clojure/clojure "1.6.0"] nil}
>user=> (add-dependencies :coordinates '[[bidi "2.1.5"]]
>#_=>                      :repositories (merge
>cemerick.pomegranate.aether/maven-central {"clojars"
>"https://clojars.org/repo"}))
>{[bidi "2.1.5"] #{[prismatic/schema "1.1.7" :exclusions
>[[org.clojure/tools.reader]]]}, [prismatic/schema "1.1.7" :exclusions
>[[org.clojure/tools.reader]]] nil}
>user=> (require 'clojure.core.memoize)
>nil
>user=> (require 'bidi.bidi)
>nil
>user=>
>```
>
>
>
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/nrepl/nrepl/issues/113#issuecomment-457860524

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by SevereOverfl0w** [comment]
I've poked at this a little longer, and we've reached the points of Clojure's internals which I don't understand. `clojure.lang.Compiler/LOADER` is bound, which utilizes a different classloader hierarchy than the context classloader.

I don't know why it is bound really. Nor do I know why this didn't work:

```
(pg/add-dependencies :coordinates '[[org.clojure/core.memoize "0.7.1"]]
                     :repositories (merge cemerick.pomegranate.aether/maven-central
                                          {"clojars" "https://clojars.org/repo"})
                     :classloader @clojure.lang.Compiler/LOADER)
```

This could be something to do with how nrepl works perhaps, or maybe to do with how Leiningen starts the JVM.

**Comment by bbatsov** [comment]
@cgrand Can you help with this one?

**Comment by thatismatt** [comment]
I hit this same problem and did a bit of digging.

The issue appears to be rooted in the fact that pomegranate generates the classloader hierarchy in a way that (in some circumstances) isn't consistent with the way `clojure.core/load` works.

It looks like pomegranate uses the `(.. Thread currentThread getContextClassLoader)` to start the search of the classloader to modify, whereas `core/load` uses `RT/baseLoader`.

I'm not sure why but it appears that lein within a project hits this issue. Here's are two repl sessions (one inside a lein project and one not) that hopefully illustrates the issue:

**Inside a lein project** - note no shared DynamicClassLoader

```
cemerick.pomegranate> (classloader-hierarchy (.. Thread currentThread getContextClassLoader))
(#object[clojure.lang.DynamicClassLoader 0x5a4932d3 "clojure.lang.DynamicClassLoader@5a4932d3"]
 #object[clojure.lang.DynamicClassLoader 0x353696bb "clojure.lang.DynamicClassLoader@353696bb"]
 #object[sun.misc.Launcher$AppClassLoader 0x4d7e1886 "sun.misc.Launcher$AppClassLoader@4d7e1886"]
 #object[sun.misc.Launcher$ExtClassLoader 0x489589c6 "sun.misc.Launcher$ExtClassLoader@489589c6"])
cemerick.pomegranate> (classloader-hierarchy (clojure.lang.RT/baseLoader))
(#object[clojure.lang.DynamicClassLoader 0x71d4bf78 "clojure.lang.DynamicClassLoader@71d4bf78"]
 #object[clojure.lang.DynamicClassLoader 0x7ad54c55 "clojure.lang.DynamicClassLoader@7ad54c55"]
 #object[clojure.lang.DynamicClassLoader 0x490a2f26 "clojure.lang.DynamicClassLoader@490a2f26"]
 #object[clojure.lang.DynamicClassLoader 0xac2c48a "clojure.lang.DynamicClassLoader@ac2c48a"]
 #object[sun.misc.Launcher$AppClassLoader 0x4d7e1886 "sun.misc.Launcher$AppClassLoader@4d7e1886"]
 #object[sun.misc.Launcher$ExtClassLoader 0x489589c6 "sun.misc.Launcher$ExtClassLoader@489589c6"])
```

**Outside a lein project** - note that the last DynamicClassLoader is shared

```
cemerick.pomegranate=> (classloader-hierarchy (.. Thread currentThread getContextClassLoader))
(#object[clojure.lang.DynamicClassLoader 0x4ea171ba "clojure.lang.DynamicClassLoader@4ea171ba"]
 #object[clojure.lang.DynamicClassLoader 0x3c83af6b "clojure.lang.DynamicClassLoader@3c83af6b"]
 #object[clojure.lang.DynamicClassLoader 0x674f6094 "clojure.lang.DynamicClassLoader@674f6094"]
 #object[clojure.lang.DynamicClassLoader 0x6b7ce79b "clojure.lang.DynamicClassLoader@6b7ce79b"]
 #object[clojure.lang.DynamicClassLoader 0x2e9577ef "clojure.lang.DynamicClassLoader@2e9577ef"]
 #object[clojure.lang.DynamicClassLoader 0xf4c7da1 "clojure.lang.DynamicClassLoader@f4c7da1"]
 #object[clojure.lang.DynamicClassLoader 0x173b9122 "clojure.lang.DynamicClassLoader@173b9122"]
 #object[sun.misc.Launcher$AppClassLoader 0x1b6d3586 "sun.misc.Launcher$AppClassLoader@1b6d3586"]
 #object[sun.misc.Launcher$ExtClassLoader 0x533bda92 "sun.misc.Launcher$ExtClassLoader@533bda92"])
cemerick.pomegranate=> (classloader-hierarchy (clojure.lang.RT/baseLoader))
(#object[clojure.lang.DynamicClassLoader 0x1af8acd1 "clojure.lang.DynamicClassLoader@1af8acd1"]
 #object[clojure.lang.DynamicClassLoader 0x22e7aa28 "clojure.lang.DynamicClassLoader@22e7aa28"]
 #object[clojure.lang.DynamicClassLoader 0x3a5ac197 "clojure.lang.DynamicClassLoader@3a5ac197"]
 #object[clojure.lang.DynamicClassLoader 0x19f89555 "clojure.lang.DynamicClassLoader@19f89555"]
 #object[clojure.lang.DynamicClassLoader 0x173b9122 "clojure.lang.DynamicClassLoader@173b9122"]
 #object[sun.misc.Launcher$AppClassLoader 0x1b6d3586 "sun.misc.Launcher$AppClassLoader@1b6d3586"]
 #object[sun.misc.Launcher$ExtClassLoader 0x533bda92 "sun.misc.Launcher$ExtClassLoader@533bda92"])
```

I also saw that `@Compiler/LOADER` returns a new DCL for each REPL evaluation, this is why @SevereOverfl0w 's [suggestion](https://github.com/nrepl/nrepl/issues/113#issuecomment-457942886) of specifying the classloader didn't work. You just need to add a call to `.getParent` to make this work, e.g.:

```
user=> (require 'clojure.core.memoize)
FileNotFoundException Could not locate clojure/core/memoize__init.class or clojure/core/memoize.clj on classpath.  clojure.lang.RT.load (RT.java:463)
user=> (require '[cemerick.pomegranate :as pg])
nil
user=> (pg/add-dependencies :coordinates '[[org.clojure/core.memoize "0.7.1"]]
          #_=>                      :repositories (merge cemerick.pomegranate.aether/maven-central
          #_=>                                           {"clojars" "https://clojars.org/repo"})
          #_=>                      :classloader (.getParent @Compiler/LOADER))
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
{[org.clojure/core.memoize "0.7.1"] #{[org.clojure/core.cache "0.7.1"] [org.clojure/clojure "1.6.0"]}, [org.clojure/core.cache "0.7.1"] #{[org.clojure/data.priority-map "0.0.7"]}, [org.clojure/data.priority-map "0.0.7"] nil, [org.clojure/clojure "1.6.0"] nil}
user=> (require 'clojure.core.memoize)
nil
```

If I can help further, please let me know.

**Comment by thatismatt** [comment]
I think I've found the reason for the bug, but I'm unsure of the right fix.

The `session/session-exec` is invoked via `server/handle` which uses `future`, which uses the agent executor, which means that when `session/session-exec` invokes `(.getContextClassLoader (Thread/currentThread))` this is the `AppClassLoader`, not one of the `DynamicClassLoader`s that correspond with `(clojure.lang.RT/baseLoader)` (i.e. `Compiler/LOADER`). So modifying the classpath at this "level" has no affect on subsequent repl evaluations.

It looks like the solution is to make sure `session/session-exec` has access to the same `DynamicClassLoader` as `(clojure.lang.RT/baseLoader)`, the simple fix of replacing `(.getContextClassLoader (Thread/currentThread))` with `(clojure.lang.RT/baseLoader)`  works, but I'm unsure if this is the "correct" thing to do. My fork, has this change: https://github.com/thatismatt/nrepl/commit/dee6e1eacfd2781113048a8a7654fd42a80b81cf

Hope this is useful.

**Comment by FiV0** [comment]
I was just wondering what the status on this is. This is also blocking the [add-lib](https://insideclojure.org/2018/05/04/add-lib/) feature from tools.deps.alpha. Maybe somebody more classpath knowledgeable can chime in to say if @thatismatt's solution is "correct" or if there is a cleaner approach. More than happy to help. Thanks

**Comment by seancorfield** [comment]
I would think reaching into `clojure.lang.RT` for the `baseLoader` was implementation details that you shouldn't rely on. What we do at work is these two lines:
```clojure
  (let [cl (.getContextClassLoader (Thread/currentThread))]
    (.setContextClassLoader (Thread/currentThread) (clojure.lang.DynamicClassLoader. cl)))
```
That's in our utility to start REBL with a Socket REPL (by default REBL also has no DCL).

**Comment by shen-tian** [comment]
I've just had a look at this issue on master, and it still stands: (I'm using `lein install` to make 0.8.0-SNAPSHOT available locally, and adding it to my `.lein/profile.clj`. In summary:

- Hotloading works outside of a project.
- Hotloading breaks inside a project, using the linked to repo as the test case.
- It does appear that the baseloader and ContextClassLoader (ctxcl) don't have a shared DynamicClassLoader as a parent, so pomegranate is modifying the closest one from ctxcl, which isn't in the stack above the baseloader... this explains why the source (e.g. bidi/bidi.cljc) is available as a resource but can't be require'd.
- Un-answered: why does this work when running outside of a project?
- We already ensure the ctxcl has a DCL (wrt @seancorfield's comment), (which was #35). See the code snippet below for where this sits now.

The solution seem to lie in the direction of using only one classloader, by either using the baseloader as ctxcl (so it gets modified by pg), which is @thatismatt 's solution, or by using the ctxcl as the baseloader, which is what we need to do while sideloading.

Either way, it's a small fix, but we are not that sure if there's a better way to do it (does it matter?) or if it's going to break something elsewhere we are not watching.

I'm happy to do some further research and suggest a way forward.

#### how `session-exec` ensures the thread has a DCL

https://github.com/nrepl/nrepl/blob/933e08b7ef0a66002bf5bf6369088515e1c4b42f/src/clojure/nrepl/middleware/session.clj#L192-L212

#### what `with-session-classloader` need to do to deal with sideloading

https://github.com/nrepl/nrepl/blob/933e08b7ef0a66002bf5bf6369088515e1c4b42f/src/clojure/nrepl/misc.clj#L64-L81

Change the last line to 

```clojure
(with-bindings {clojure.lang.Compiler/LOADER ctxcl#}
         ~@body)
```
also works as a fix.

**Comment by bbatsov** [comment]
> Either way, it's a small fix, but we are not that sure if there's a better way to do it (does it matter?) or if it's going to break something elsewhere we are not watching.

Let's go with the fix and see how it goes during the testing of nREPL 0.8. I'll probably cut some alpha in a week or two and ship it to my unfortunate CIDER users who are using MELPA. :-)

**Comment by shen-tian** [comment]
Cool. Will open a PR in a moment. I'd like to try understand this issue a bit more for myself, but feeling reasonably OK about the fix.

**Comment by shen-tian** [comment]
Not sure if we want to re-open this, but changes in #210 means this is probably not working under Java 8 anymore.
