### ISSUE TITLE
Support custom value rendering middleware

### ISSUE THREAD

**Issue by cemerick** [nrepl/nrepl#12]
Currently, nREPL's interruptible-eval middleware hardcodes a dependency on pr-values. It would be nicer if the user could either specify alternate rendering middleware or if nREPL's built-in middleware accepted an arbitrary function to render values with. Specifically, this would enable pretty-printing REPL output.

I've set up a middleware to demonstrate this, in combination with the Puget printing library:
https://github.com/greglook/whidbey

Currently it is possible to replace the default middleware, but it involves some ugly runtime metadata manipulation which reaches into the nREPL internals. Addressing this would be another step towards simplifying pretty-printing/color integration in the REPL.

(from https://dev.clojure.org/jira/browse/NREPL-55)

**Comment by bbatsov** [comment]
@greglook Would you be interested in contributing this upstream? 

Now we're back in the business of accepting PRs! 🎉

**Comment by arrdem** [comment]
Hummmm this could also drastically simplify the implementation of content-type handlers...

**Comment by greglook** [comment]
Might be able to look at this in a few days; it'd certainly be nice to ditch the metadata wrangling.

**Comment by bbatsov** [comment]
@greglook Certainly! 👍
