### ISSUE TITLE
Using `:greeting-fn` breaks client connections (or docs on how to use it is missing)

### ISSUE THREAD

**Issue by holyjak** [nrepl/nrepl#124]
## Expected behavior

When I run nrepl server like this, with a `:greeting-fn`:

```clj
shell$ clj -R:nrepl
user=> (require '[nrepl.server :refer [start-server stop-server]])
user=> (start-server :greeting-fn (fn [t] (send t {:out "Welcome!\n=>"})))
#nrepl.server.Server{:server-socket #object[java.net.ServerSocket 0x7cb2651f "ServerSocket[addr=/127.0.0.1,localport=52395]"], :port 52395, :open-transports #object[clojure.lang.Atom 0x47ec7422 {:status :ready, :val #{}}], :transport #object[nrepl.transport$bencode 0xf3fcd59 "nrepl.transport$bencode@f3fcd59"], :greeting #object[user$eval1435$fn__1436 0x79d743e6 "user$eval1435$fn__1436@79d743e6"], :handler #object[nrepl.middleware$wrap_conj_descriptor$fn__886 0x64c4c01 "nrepl.middleware$wrap_conj_descriptor$fn__886@64c4c01"]}
```
and try to connect to it:

```sh
shell$ clj -R:nrepl -m nrepl.cmdline --connect --host 127.0.0.1 --port 52395
```

then I should see the greeting message and nrepl prompt.

## Actual behavior

Instead, this happens in the client:

```sh
shell$ clj -R:nrepl -m nrepl.cmdline --connect --host 127.0.0.1 --port 52395
Exception in thread "main" java.net.SocketException: The transport's socket appears to have lost its connection to the nREPL server
	at nrepl.transport$bencode$fn__728$fn__729.invoke(transport.clj:95)
	at nrepl.transport$bencode$fn__728.invoke(transport.clj:95)
	at nrepl.transport$fn_transport$fn__684.invoke(transport.clj:42)
...
```

PS: If I change the greeting fn to a "no operation" like this: `:greeting-fn (fn [t] nil)` then the client connection works.

## Steps to reproduce the problem

See above. The `-R:nrepl` profile is copy-paste [from nREPL docs](https://nrepl.org/nrepl/usage/server.html#_using_clojure_cli_tools):

```edn
{
:aliases {
       :nrepl {:extra-deps {nrepl/nrepl {:mvn/version "0.5.0"}}}
  }
}

## Environment & Version information

### Clojure version

1.9.0, 1.10.0

### Java version

1.8, 11.0.1

### Operating system

OSX

### nREPL

0.5.0, 0.5.3

**Comment by cichli** [comment]
Should the `send` in the first example be `nrepl.transport/send`? If you're accidentally calling `clojure.core/send` it should throw a `ClassCastException` [here](https://github.com/nrepl/nrepl/blob/2d5a4c89d843c9941128c99d627b8c8be4974bf3/src/clojure/nrepl/server.clj#L45) but possibly something is hiding the error.

**Comment by holyjak** [comment]
Update: When I use tty then it is also broken:

```clj
(start-server :port 55555 :greeting-fn (fn [t] (send t {:out "Welcome!\n=>"})) :transport-fn transport/tty)
```

leads to

```
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
Connection closed by foreign host.
```

But if I used the provided greeting, it works:

```clj
(start-server :port 55555 :greeting-fn transport/tty-greeting :transport-fn transport/tty)
```

=>

```
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
;; nREPL 0.5.3
;; Clojure 1.10.0
user=>
```

so the question is what is the crucial difference between `transport/tty-greeting` and my `(fn [t] (send t {:out "Welcome!\n=>"}))`?!

**Comment by holyjak** [comment]
Thank you, @cichli , you were right! I was by mistake calling `clojure.core/send` instead of `nrepl.transport/send`! I will look into improving the docs / code to help others not to make the same mistake.
