### ISSUE TITLE
Please cut a release with clj 1.10 support/minimal dep chain

### ISSUE THREAD

**Issue by ehashman** [nrepl/nrepl#129]
Hi nrepl maintainers!

I'm trying to get Leiningen 2.9.0 (not yet released) packaged for the Debian Buster freeze. It has a dependency on nrepl, but the version of nrepl it depends on has a dep on bencode, which seems to have been vendored into nrepl since 0.5.3. I don't want to have to upload that separately, so I am currently testing a Leiningen build against nrepl HEAD. As well, I'm interested in the Clojure 1.10 support so I can upgrade Clojure 1.9 -> 1.10 in Debian without patching.

Would you be able to cut a release so we can update Leiningen to depend on nrepl 0.6.0?

Cheers!

**Comment by bbatsov** [comment]
I’m on vacation (traveling without a computer), but @cichli will cut a new release soon. I think currently the code is in a releasable state.

Sorry about the `bencode` package back and forth - that’s on me.

**Comment by bbatsov** [comment]
Roger that! I didn’t even know Debian packaged Clojure libraries. That’s pretty cool!

**Comment by cichli** [comment]
I've released [0.6.0](https://github.com/nrepl/nrepl/releases/tag/0.6.0) now 🎉.

@bbatsov could you give me push rights for https://github.com/nrepl/nrepl.org so I can push the regenerated docs?

**Comment by ehashman** [comment]
Thanks all!! My snapshot was [accepted last night](https://tracker.debian.org/news/1027615/accepted-nrepl-clojure-06020190204git176bde868-1-source-all-into-unstable-unstable/) so I'll go ahead and upgrade to the real 0.6.0 :)

**Comment by bbatsov** [comment]
@cichli Done.

**Comment by bbatsov** [comment]
@cichli Try now. I think I got it right this time.

**Comment by cichli** [comment]
@bbatsov all good now, thanks! 🙇
