### ISSUE TITLE
Interrupt of load-file generates java.lang.ThreadDeath exception

### ISSUE THREAD

**Issue by cemerick** [nrepl/nrepl#13]
At lein prompt (load-file "src/test/core.clj") where core.clj contains (Thread/sleep 10000) then C-c to interrupt.

```
CompilerException java.lang.ThreadDeath, compiling/home/vitoshka/tmp/cidertest/src/blabla/core.clj:1:17)
clojure.lang.Compiler.load (Compiler.java:7142)
clojure.lang.Compiler.loadFile (Compiler.java:7086)
clojure.lang.RT$3.invoke (RT.java:318)
user/eval3418 (form-init8959987907704530559.clj:1)
clojure.lang.Compiler.eval (Compiler.java:6703)
clojure.lang.Compiler.eval (Compiler.java:6666)
clojure.core/eval (core.clj:2927)
clojure.main/repl/read-eval-print-6625/fn-6628 (main.clj:239)
clojure.main/repl/read-eval-print--6625 (main.clj:239)
clojure.main/repl/fn--6634 (main.clj:257)
clojure.main/repl (main.clj:257)
clojure.tools.nrepl.middleware.interruptible-eval/evaluate/fn--594 (interruptible_eval.clj:67)
Caused by:
ThreadDeath
java.lang.Thread.stop (Thread.java:836)
clojure.tools.nrepl.middleware.interruptible-eval/interruptible-eval/fn--636 (interruptible_eval.clj:204)
clojure.tools.nrepl.middleware/wrap-conj-descriptor/fn--408 (middleware.clj:17)
clojure.tools.nrepl.middleware.pr-values/pr-values/fn--573 (pr_values.clj:17)
clojure.tools.nrepl.middleware/wrap-conj-descriptor/fn--408 (middleware.clj:17)
clojure.tools.nrepl.middleware.load-file/wrap-load-file/fn--751 (load_file.clj:77)
clojure.tools.nrepl.middleware/wrap-conj-descriptor/fn--408 (middleware.clj:17)
clojure.tools.nrepl.middleware.session/add-stdin/fn--710 (session.clj:235)
clojure.tools.nrepl.middleware/wrap-conj-descriptor/fn--408 (middleware.clj:17)
cider.nrepl.middleware.test/wrap-test/fn--3003 (test.clj:199)
clojure.tools.nrepl.middleware/wrap-conj-descriptor/fn--408 (middleware.clj:17)
cider.nrepl.middleware.stacktrace/wrap-stacktrace/fn--2909 (stacktrace.clj:146)
```

In CIDER, eval the buffer with C-c C-k which uses load-file op and then C-c C-b to interrupt. The relevant CIDER issue is [here](https://github.com/clojure-emacs/cider/issues/869).

(from https://dev.clojure.org/jira/browse/NREPL-69)

**Comment by vspinu** [comment]
I might have a look but I already have quite a backlog of promised open source fixes here and elsewhere :/ This issues is from 2014 and it looks like it's not very high priority.

**Comment by mallt** [comment]
I'm trying to debug this using the `clj` tool, but pressing `C-c` quits the `clj` tool instead of sending an interrupt. Does anybody perhaps know how to send an interrupt operation from the `clj` tool?

Alternatively, what would be the best way to make `lein repl` use my local version of nREPL?

Thanks for the help!

**Comment by bbatsov** [comment]
@mallt Well, it'd be nice if we captured `C-c` in the terminal and had it send interrupt (and a `C-c` without a request can simply exit or something). Some more graceful handling of `C-c` and `C-d` have been on my mind for a while, but I never found the time for those. https://github.com/trptcolin/reply already does this, so I guess you can borrow some code from there or just use reply to debug this (e.g. from `lein repl/boot repl`).

**Comment by mallt** [comment]
Ok thanks @bbatsov! I'll check how to make reply use my local version of nREPL.

**Comment by bbatsov** [comment]
@mallt Looks like a good approach to me. I don't envision any unexpected problems with this.
