### ISSUE TITLE
Intermittent test failure relating to streamed-printing and bencode.

### ISSUE THREAD

**Issue by shen-tian** [nrepl/nrepl#132]
## Expected behavior

CI tests should consistently pass or fail

## Actual behavior

CI tests are failing intermittently on different Java and Clojure versions, both on Travis and CircleCI

### Examples:

CircleCI [link](https://circleci.com/gh/nrepl/nrepl/9) Java 11, Clojure 1.10

```
lein test nrepl.core-test

lein test :only nrepl.core-test/streamed-printing

ERROR in (streamed-printing) (bencode.clj:177)
bencode transport
 respects buffer-size option
expected: (= [{:value "(0 1 2 3"} {:value " 4 5 6 7"} {:value " 8 9 10 "} {:value "11 12 13"} {:value " 14 15)"} {:ns "user"} {:status ["done"]}] (->> (message client {:op :eval, :code (code (range 16)), :nrepl.middleware.print/stream? 1, :nrepl.middleware.print/buffer-size 8}) (mapv (fn* [p1__3565#] (dissoc p1__3565# :id :session)))))
  actual: java.lang.ClassCastException: class clojure.lang.PersistentArrayMap cannot be cast to class [B (clojure.lang.PersistentArrayMap is in unnamed module of loader 'app'; [B is in module java.base of loader 'bootstrap')
 at nrepl.bencode$string_LT_payload.invokeStatic (bencode.clj:177)
    nrepl.bencode$string_LT_payload.invoke (bencode.clj:177)
    nrepl.bencode$read_map$fn__375.invoke (bencode.clj:291)
    clojure.core$map$fn__5847$fn__5848.invoke (core.clj:2742)
    clojure.core$partition_all$fn__8520$fn__8521.invoke (core.clj:7264)
    clojure.core.protocols$fn__8144.invokeStatic (protocols.clj:168)
    clojure.core.protocols/fn (protocols.clj:124)
```
Travis [link](https://travis-ci.org/nrepl/nrepl/jobs/504008959) Java 8, Clojure 1.10

```
lein test nrepl.core-test
lein test :only nrepl.core-test/streamed-printing
ERROR in (streamed-printing) (bencode.clj:177)
bencode transport
 respects buffer-size option
expected: (= [{:value "(0 1 2 3"} {:value " 4 5 6 7"} {:value " 8 9 10 "} {:value "11 12 13"} {:value " 14 15)"} {:ns "user"} {:status ["done"]}] (->> (message client {:op :eval, :code (code (range 16)), :nrepl.middleware.print/stream? 1, :nrepl.middleware.print/buffer-size 8}) (mapv (fn* [p1__3565#] (dissoc p1__3565# :id :session)))))
  actual: java.lang.ClassCastException: clojure.lang.PersistentArrayMap cannot be cast to [B
 at nrepl.bencode$string_LT_payload.invokeStatic (bencode.clj:177)
    nrepl.bencode$string_LT_payload.invoke (bencode.clj:177)
    nrepl.bencode$read_map$fn__375.invoke (bencode.clj:291)
    clojure.core$map$fn__5847$fn__5848.invoke (core.clj:2742)
```

Travis [link](https://travis-ci.org/nrepl/nrepl/jobs/504838033) Java 11, Clojure 1.7

```
lein test nrepl.core-test
lein test :only nrepl.core-test/streamed-printing
ERROR in (streamed-printing) (bencode.clj:177)
bencode transport
Uncaught exception, not in assertion.
expected: nil
  actual: java.lang.ClassCastException: class clojure.lang.PersistentArrayMap cannot be cast to class [B (clojure.lang.PersistentArrayMap is in unnamed module of loader 'app'; [B is in module java.base of loader 'bootstrap')
 at nrepl.bencode$string_LT_payload.invoke (bencode.clj:177)
    nrepl.bencode$read_map$fn__222.invoke (bencode.clj:291)
    clojure.core$map$fn__4549$fn__4550.invoke (core.clj:2611)
    clojure.core$partition_all$fn__6811$fn__6812.invoke (core.clj:6971)
    clojure.core.protocols/fn (protocols.clj:167)
    clojure.core.protocols$fn__6478$G__6473__6487.invoke (protocols.clj:19)
    clojure.core.protocols$seq_reduce.invoke (protocols.clj:31)
    clojure.core.protocols/fn (protocols.clj:101)
    clojure.core.protocols$fn__6452$G__6447__6465.invoke (protocols.clj:13)
    clojure.core$transduce.invoke (core.clj:6590)
    clojure.core$into.invoke (core.clj:6604)
    nrepl.bencode$read_map.invoke (bencode.clj:289)
    nrepl.bencode$read_bencode.invoke (bencode.clj:261)
```

**Comment by bbatsov** [comment]
I'll assign this to @cichli, as it seems it's related to the print streaming.

**Comment by shen-tian** [comment]
Adding more notes to this bugbear. I'm fairly sure it's this test:

https://github.com/nrepl/nrepl/blob/598467a8b6033b7c8756bfa9bf57359b0e50986a/test/clojure/nrepl/core_test.clj#L384-L395

Looking at the test, this is actually a bit of a load test for the printer/system as a whole. Typing `(range)` into a repl is not recommended.

I just this in real life (starting nrepl with clj, cider-connect with Cider 0.21) and it pretty much blew up, not responding to `C-c C-c`. (It was starting to stream the output)

The error itself is on bencode read, where it's getting a map when it was expecting a key. What I'm thinking:

- There's a hidden issue with the bencode encoder/decoder, where it can't read something it can write.
- The streaming printer, when just dumping bytes non-stop, is generating an error that's triggering this error mode.
- On a CI, the 100ms test is enough to trigger this error, but not on a dev machine?

🕵️ ongoing...

**Comment by shen-tian** [comment]
Adding more notes to this, after discussion with @cichli on Slack: 

- The interrupt is killing the thread with a `.stop` call. This means it's stopping half way through writing a bencode message. Without the closing delimiter, `e`, it's reading the next message (a map) in as a key.
- c99280bbf9078e5b3f96a7ec23f89ea2425b9a4e was an attempt to fix this, but most likely traded an intermittent timeout failure with a quick failure.

**Comment by shen-tian** [comment]
I'm very sure this is a bug now. It was introduced in adb1c1427f47a7398e28275bbb0ac5a36d58ae04. 

The test commented out by #160 demonstrates this.:

- It will reliably fail on my local machine with `:nrepl.middleware.print/buffer-size` set to 100000 (from the default of 1024).
- removing `.stop` from this line https://github.com/nrepl/nrepl/blob/cdd688f22e65580e9b52d9a8def9ad42a530914a/src/clojure/nrepl/middleware/session.clj#L196 seems to fix it. This seems to be under discussion in #158 as well.

Given the lack of noise/complaints around this, bar #158, I'm not sure how big a deal this is tbh.
