### ISSUE TITLE
Are op names keywords or strings?

### ISSUE THREAD

**Issue by shen-tian** [nrepl/nrepl#138]
### Why does it matter

Stability and backwards compatibility is NB for nREPL. Right now, the string/keyword specification of messages is largely implied by the limitations of bencode transport. With the EDN transport (and transit one too?), we get the chance to be more exact about what messages look like. But also, we need to take some care to define a stable default behaviour. 

For example, all four of these messages look the same once ran through the bencode write/read and keywordizing cycle:

```clj
{:op :eval :code "(+ 2 2)"}
{:op "eval" :code "(+ 2 2)"}
{"op" "eval" :code "(+ 2 2)"}
{"op" "eval" "code" "(+ 2 2)"}
```

Do we want to accept all four going forward? Even if we all requests to be permissive, we should still give some guarantees that responses follow a consistent format. (I'm thinking of `describe` and `unkown-op`, which need to provide `:op` values).

As it sits in master, the EDN transport accepts only the first two, but responds with keywords.

### What do we think it should be

This is mixed, but lean towards keywords: this is what [nrepl.org](https://nrepl.org/nrepl/ops.html) refers to and what's used in @bbatsov's [blog posts](https://metaredux.com/posts/2019/03/29/nrepl-0-6.html). Internally, all the unit tests (so far as they can be used as examples) use keywords.

However, this is not [done consistently](https://metaredux.com/posts/2019/01/12/nrepl-beyond-clojure.html). Other texts discussing nrepl also refer to ops as strings [e.g.](https://lambdaisland.com/guides/clojure-repls/clojure-repls#org1355f8e). 

### What happens under the hood.

It's all strings. Both this project but also all the middlewares, first and third party.

**Comment by bbatsov** [comment]
I see 3 messages and they are exactly the same. :D 

I get your point, though. I think both keywords and strings should be accepted and internally we should stick to keywords as their representation. In the responses they should be keywords IMO (if the transport can deal with keywords).

**Comment by shen-tian** [comment]
As a matter of protocol definition, I like the "keyword if you can" too. Possibly for stylistic reasons.

I had a go at converting nrepl to all keywords, and it looks something like this: https://github.com/nrepl/nrepl/compare/master...shen-tian:keywordize-ops

The good thing is that the EDN/Transit transports can be entirely transparent. But this is going to cause lots of messy compatibility problems with other middlewares, isn't it? The matching of op names is done by the middlewares themselves, so we can't have nrepl make that switch for them. 

The two other options I can imagine are 

1. Have keywords external, and strings internal. No compatibility problems, but we need to insert some coercion code somewhere to do the translation, and we'll always have the confusing internal/external representations.

2. Follow the path of least resistance and embrace the strings. That way, we get transparent EDN/transit transports, consistency between messages and internals, and don't need any changes from other middlewares.

In all cases, we can be lenient on what we accept. We do need to take a position on what we return.

**Comment by bbatsov** [comment]
> The good thing is that the EDN/Transit transports can be entirely transparent. But this is going to cause lots of messy compatibility problems with other middlewares, isn't it? The matching of op names is done by the middlewares themselves (e.g. cider-nrepl only knows what to do with "complete" not :complete), so we can't have nrepl make that switch for them.

Yeah, unfortunately this has leaked to place where it should have. Op names should have been kept as symbols internally, but this didn't happen for one reason or another.

> Follow the path of least resistance and embrace the strings. That way, we get transparent EDN/transit transports, consistency between messages and internals, and don't need any changes from other middlewares.

I think that'd be wiser. We just accept we're stuck with strings and are done with it. 

> Hope I'm not making a mountain out of a mole hill here. But it feels like this is worth being decided on, then well documented.

I completely agree. We have to be consistent and we have to document all of this properly.

**Comment by shen-tian** [comment]
I can work on some documentation. Worth getting some other opinions?

**Comment by bbatsov** [comment]
We can always ping @nrepl/nrepl for extra feedback. If someone responds differently we'll discuss that, if not you can move forward with the documentation.

**Comment by bbatsov** [comment]
Seems we won't be getting more feedback. :-)

**Comment by arrdem** [comment]
I'd lean towards keywords only for things which are protocol specified. Keywords are for enum values IMO, not just syntactically nicer strings. As I recall, ops are dynamically defined and discovered via middleware for all there are some standard ones, so I'd personally lean towards strings for all yes it is less nice and existing clients may be more featureful.
