### ISSUE TITLE
Use clojure.spec to describe the request/response format

### ISSUE THREAD

**Issue by bbatsov** [nrepl/nrepl#140]
That's something we've discussed a while ago with @shen-tian. I'm just adding the ticket here, so we won't forget about this. 

As nREPL's requests and responses are just plain old maps they are perfect candidates to get some spec love.

**Comment by djblue** [comment]
Is anyone actively working on this?

**Comment by bbatsov** [comment]
@djblue I don't think so. @shen-tian intended to work on this, but I guess he didn't find any time.

**Comment by shen-tian** [comment]
Hey. I actually had a go at this a while back: 

https://github.com/shen-tian/nrepl/blob/adding-spec/src/spec/nrepl/spec.clj

Writing the spec wasn't too hard, but how and where to use it was more an open question, especially given it's not supported in the earlier clojure versions. Some ideas:

- Add as part of unit testing on Clojure 1.9 and 1.10
- Add a dev time guard
- Only as documentation?

I doubt we want to use spec at runtime, especially as spec errors won't be much use to end users?

**Comment by bbatsov** [comment]
> Add as part of unit testing on Clojure 1.9 and 1.10

This seems like a good idea to me, but I'm open to using the specs during development as well.
