### ISSUE TITLE
how to distinguish user eval ops from middleware ones ?

### ISSUE THREAD

**Issue by murtaza52** [nrepl/nrepl#148]
Hi,

I am working on a middleware where I want to need to log any commands executed by the user. 

Below is my code - 

`
(defn log-commands
  [handler]
  (fn [{:keys [code] :as msg}]
    (when (and (string? code)
               (not (blank? code)))
      (hlc/log-info "hsrepl command" {:event :hsrepl-command :command code}))
    (handler msg)))

(set-descriptor! #'log-commands {:requires #{}
                                 :expects #{"eval"}
                                 :handles {}})

`

The problem is that when the client repl connects to the server, it also logs the initial code injections from the middlewares. How do I distinguish between code that is injected by the middleware and that entered by the user ? 

Thanks,
Murtaza

**Comment by bbatsov** [comment]
I'm guessing the eval session is probably different for the user evaluations and those that come from the middleware, so I'd start there.

**Comment by murtaza52** [comment]
however that doesn't help me, bcoz I have no way to distinguish that an eval session of the middleware from an eval session of the user. Or is there a way ?

In the documentation, I read about the `values` slot, however I dont see the key when I print out the params passed in the middleware. Maybe that could help me distinguish between code that was sent by the user and code that was injected by the middleware ?

**Comment by shen-tian** [comment]
Thinking about this a bit more, I'm not sure this is something nrepl itself can deal with, as the middlewares are, and should be, relatively ignorant of what happens before/after them.

For your use case, can you modify message client side? That would be probably the best place to tag messages as `sent-by-a-human`, which your own middleware can use?
