### ISSUE TITLE
Fix broken cross references in documentation

### ISSUE THREAD

**Issue by plperron** [nrepl/nrepl#149]
Some page references are broken and point back to the current page. Some of the page cross references ending with an '#' are working as expected. However, the official antora documentation urges toward using the xref macro for page cross references instead of the double angled brackets syntax `<< reference.adoc >>`.

 Examples of reference pointing back to the same page.
    
      - doc/modules/ROOT/pages/index.adoc:49
      - doc/modules/ROOT/pages/index.adoc:60
      - doc/modules/ROOT/pages/design/handlers.adoc:16
      - doc/modules/ROOT/pages/design/middleware.adoc:39
      - doc/modules/ROOT/pages/design/middleware.adoc:108
      - doc/modules/ROOT/pages/design/overview.adoc:4

    References:
    
      - https://docs.antora.org/antora/2.0/asciidoc/page-to-page-xref/
      - https://docs.antora.org/antora/2.0/asciidoc/in-page-xref/

**Comment by bbatsov** [comment]
Thanks for spotting and fixing this. Guess I'll have to review the CIDER documentation for this problem as well.
