### ISSUE TITLE
Document how to embed nREPL in a Java application

### ISSUE THREAD

**Issue by bbatsov** [nrepl/nrepl#151]
This question gets asked from to time to time, so it'd be nice if we just had the answer in the docs.

**Comment by jmingtan** [comment]
Hi, I'd like to work on this issue, if no one is already working on it!

To that end, I've created an example project with how I think nrepl can be embedded in Java: https://github.com/jmingtan/nrepl-java-example. If this looks sound, I'll start updating the documentation and PR.

If you think the example project might be useful I'll link to it as well.

**Comment by bbatsov** [comment]
> Hi, I'd like to work on this issue, if no one is already working on it!

Happy to hear this!

> To that end, I've created an example project with how I think nrepl can be embedded in Java: https://github.com/jmingtan/nrepl-java-example. If this looks sound, I'll start updating the documentation and PR.

Yep, that's the right approach. One thing you can potentially add is adding some extra middleware to the server, but that's not essential. 

> If you think the example project might be useful I'll link to it as well.

I think it's useful. Potentially we can have it in the nREPL org for posterity's sake.

**Comment by jmingtan** [comment]
Great idea, I will work on your suggestion and in the meantime I'll transfer the repository as well.

**Comment by bbatsov** [comment]
I've just invited you to the GitHub org. Once you accept the invite you'll be able to transfer the repo.

**Comment by shen-tian** [comment]
This is closed?

**Comment by bbatsov** [comment]
Indeed. Thanks for the reminder!
