### ISSUE TITLE
Naming convention for default-middlewares

### ISSUE THREAD

**Issue by MalloZup** [nrepl/nrepl#155]
HI!
I'm reading through the codebase, and afaik I find personally inconsistent the way we name the default middlewares. ( I might don't have all the context information however)

https://github.com/nrepl/nrepl/blob/master/src/clojure/nrepl/server.clj#L81

E.g some of them use the prefix `wrap` some not. I was thinking that perhaps we should either call them all  with the `wrap` prefix, like `wrap-stdin` instead of `add-stdin`, or use another prefix but wrap sound ok to me.

It is not really a major issue only something I just spotted and wanted to ask . :grin: 

Tia

**Comment by MalloZup** [comment]
If I see for example https://github.com/clojure-emacs/cider-nrepl/blob/master/src/cider/nrepl.clj#L500, we use there the `wrap-` prefix.

Imho if we agree on this convention we should:

1) rename here.
2) add perhaps a line in some documentation 

For this I can send a PR. Regarding point 2 I might need some guidance where to add the doc :flower_playing_cards:

**Comment by bbatsov** [comment]
> E.g some of them use the prefix wrap some not. I was thinking that perhaps we should either call them all with the wrap prefix, like wrap-stdin instead of add-stdin, or use another prefix but wrap sound ok to me.

I'll have to take a closer look, as I'm not really sure what was Chas's reasoning back in the day. It'd be nice if we adopted some common conventions, but we can't really rename anything as that'd be a breaking change. I always use `wrap-something` when creating middlewares.

**Comment by MalloZup** [comment]
Thx. Yep I was asking me about breaking changes but I didn't know who is the consumer of that Middleware functions e. G the client also? Anyways yep make sense, we can just perhaps add comment in the default handler saying that new Middleware should use wrap and also add it somewhere in docs. 👀📡🎸🎶🎹🎹🐶😎🎷

**Comment by bbatsov** [comment]
Clients don't know middleware names, but other middlewares might be depending on those, that's why changing them should be avoided. 

I completely agree we should improve the docs.

**Comment by MalloZup** [comment]
We could create a documentation page, under `hacking on nRepl` we could create `hacking on nRepl middlewares/extension` new section with a page like guidelines or something like this..  In this way we could add this guidelines

**Comment by MalloZup** [comment]
addressing this partially by https://github.com/nrepl/nrepl/pull/156 ( at least in code).  The rest highlevel doc, imho we just need to add a page in `nrepl` centralized fashion

**Comment by bbatsov** [comment]
> We could create a documentation page, under hacking on nRepl we could create hacking on nRepl middlewares/extension new section with a page like guidelines or something like this.. In this way we could add this guidelines for middlewares and ( new client perhaps )

Yeah, that has been on my todo list for a while now and I hope to do it during the Clojurists Together funding round. 

I've also realized it might be a good idea to be able to create raw handlers if someone wants to change some core middleware in some weird situation.

**Comment by shen-tian** [comment]
What do you mean by raw handlers?

**Comment by bbatsov** [comment]
@shen-tian Good question! Now I can't remember what I meant myself. 😆

**Comment by bbatsov** [comment]
I'm assuming I meant creating some custom handler that doesn't include all of `default-middleware`. Probably I meant we need to document how this can be done.

**Comment by MalloZup** [comment]
yes afaik this issue was just about the naming of default middleware and their related prefix which are not consistent, afaik and some doc about it. nothing really urgent

**Comment by bbatsov** [comment]
See https://nrepl.org/nrepl/building_middleware.html#_naming_conventions
