### ISSUE TITLE
Confused about interrupt

### ISSUE THREAD

**Issue by FreekPaans** [nrepl/nrepl#158]
(Not sure if this is the right place to ask this question, please refer me to the right place if it's not).

I was running into some issues with interrupting evaluation from CIDER, and decided to dive into the code a bit for what's going on (great work BTW, was very readable!). There I found [this particular line](https://github.com/nrepl/nrepl/blob/master/src/clojure/nrepl/middleware/session.clj#L190), which (I think) is used for actually interrupting the thread:

```clj
(doto ^Thread @thread .interrupt .stop)
```

Now, I think (haven't investigated further) my issue is caused by a race between `.stop` and `.interrupt`, but that doesn't really matter for my questions: 

* Why is `.stop` used here? AFAIK using this is [inherently unsafe](https://docs.oracle.com/javase/8/docs/api/java/lang/Thread.html#stop--), and I've actually ran into issues where I needed to restart the REPL.
* If `.stop`ing _is_ intended, I think the naming is confusing here. I think someone coming from a Java background would expect `.interrupt`, but not a `.stop` also. What do you think?

Thanks in advance!

**Comment by bbatsov** [comment]
Frankly, I've got no idea why the extra `.stop` is needed - I was under the impression that usually `.interrupt` is all you'd need. @cgrand, what's the reason to have to stop the thread after interrupting it?

**Comment by FreekPaans** [comment]
I can imagine that `.stop` will be able to stop the thread in cases where `.interrupt` cannot, but at the expense of potentially corrupting the state of the process. So I guess it's a bit of a judgement call - personally I think you should only interrupt. Of course if the thread doesn't stop you can still "move over" to a new thread for evaluating new code.

**Comment by bbatsov** [comment]
Probably you're right. I guess we can try switching to just using `.interrupt`. @nrepl/nrepl any thoughts on the subject?

**Comment by shen-tian** [comment]
> Probably you're right. I guess we can try switching to just using `.interrupt`. @nrepl/nrepl any thoughts on the subject?

After [looking around a bit](https://stackoverflow.com/questions/20527893/java-thread-stop-vs-thread-interrupt/20528033), this doesn't actually stop the thread. It only works for threads that uses `Thread.interrupted()` to control their own termination.

The TL:DR; of this is there's no reliable AND safe way to stop a tread without the thread's cooperation. Given nREPL's dev tool nature, it's probably better to try `.stop` even if it might corrupt the process?

One fair question is do we want to give threads that respect the interrupted flag a chance to cleanly exit before bringing in the `.stop` hammer? Assume that's what @SevereOverfl0w is suggesting?

@FreekPaans: does this fit your use case?

**Comment by bbatsov** [comment]
Btw, from the link you've posted it seems that `interrupt` does nothing except set a flag that the thread is supposed to honour and interrupt itself, so I do wonder if does anything for us. Java concurrency is hard... :D

**Comment by FreekPaans** [comment]
> Btw, from the link you've posted it seems that `interrupt` does nothing except set a flag that the thread is supposed to honour and interrupt itself, so I do wonder if does anything for us. Java concurrency is hard... :D

Yeah, fortunately a lot of APIs respect the interrupt flag.

> One fair question is do we want to give threads that respect the interrupted flag a chance to cleanly exit before bringing in the .stop hammer? Assume that's what @SevereOverfl0w is suggesting?

> @FreekPaans: does this fit your use case?

Yes it would, though ideally it would optionally `.stop` it - in some case I'd rather have the thread blocked (with nrepl using a new one), then have it stopped with `.stop` and messing up some shared state.

> Under what conditions does it corrupt state?

I'm not too familiar with Java script locking, but any monitors bound to the thread will be released, as far as I can tell. I can imagine Clojure itself using some of this for its internals, e.g. dynamic vars, but not sure.
