### ISSUE TITLE
out-of-the-box completion

### ISSUE THREAD

**Issue by technomancy** [nrepl/nrepl#174]
It's rather silly that completion doesn't work out of the box when you run `lein repl`. I'm interested in fixing this problem, but there are two different possible approaches, and I'd like some input about which one is preferable from the perspective of the nrepl reference implementation. We already support completion for non-nrepl sessions, so the `clojure-complete` library is already present.

**Describe the solution you'd like**

One way is to make it so the nrepl server itself handles `op="complete"` messages natively without any middleware.

**Describe alternatives you've considered**

The other is for Leiningen's `repl` task to default to inserting middleware which handles the `complete` op. If we go this route, no changes would need to be made in this codebase.

**Additional context**

This would make it so a manual installation of the `cider/nrepl` middleware isn't required for such a basic thing as completion, but of course it'd still be needed for other features.

**Comment by bbatsov** [comment]
I've also been thinking that it makes sense to promote `complete` to a built-in op, but we'll have to reimplement the completion functionality internally in order to comply with our 0 runtime deps policy. This will probably limit the middleware to some relatively basic default functionality, as it doesn't make sense to re-implement something as complex and full-featured as `compliment`. Probably that's not a big deal, as other middlewares can easily "take over" the default op and augment it. 

 I'm guessing we can also have an official `nrepl-complete` middleware and have some inlined dependency there as an alternative. It's not like we can't inline something directly into nREPL, I've just never been too fond of this approach of dealing with deps.

**Comment by bbatsov** [comment]
Btw, same reasoning probably applies to `var-info` (which deserves a better name e.g. `describe-symbol` or something like this) - like completion it's a pretty fundament operation that is probably going to be useful in many environments for things like definition lookup. Or perhaps definition lookup should be some basic op. Haven't had much time to think about this lately.

**Comment by arichiardi** [comment]
Completion could be pretty basic indeed especially on the Clojure side. I like the idea.

**Comment by bbatsov** [comment]
I see that the `clojure-complete` code is just 100 lines and it was actually copied from `swank-clojure`, so I guess copying it to nREPL and tweaking it a bit would be a reasonable solution.

**Comment by technomancy** [comment]
Great; thanks. Even if the out-of-the-box completion only worked on Clojure vars and not Java classes, it would be an improvement.

One other request: if this becomes part of nrepl itself, it would be nice if it could be documented as some kind of optional standardized extension to the nrepl protocol so that if clients implement it, they can also get the same functionality on other servers.

**Comment by bbatsov** [comment]
Yeah, absolutely. There's one thing that we need to agree on before moving to the implementation - the op name and the params. Probably it'd be a good idea to avoid reusing the name used by `cider-nrepl` to avoid breakages. On the other hand `complete` is a great op name. Any ideas/suggestions? 

As for the supported params - probably they should be the same that `complete` currently takes, even if the simple completion would ignore the context for now.

**Comment by technomancy** [comment]
I think that while `complete` is a good name for the command, it's not a good name for the nrepl op, because it's imperative. Either `completions-for` or `completions` would be better since you're querying for a piece of data.

**Comment by bbatsov** [comment]
FYI - I've started working on this, but it's going to take me a while to adapt the code from `clojure-complete`, as it just returns a sequence of candidates as string, and we should ideally return the candidates as maps with some metadata (e.g. their type - function, macro, special, etc).

**Comment by bbatsov** [comment]
Small update - I already have a version of the middleware running locally and I hope to submit the code in the next several days.
