### ISSUE TITLE
Howto connect to an NREPL running in Docker

### ISSUE THREAD

**Issue by twashing** [nrepl/nrepl#176]
I asked [this question](https://stackoverflow.com/questions/59761121/howto-connect-to-nrepl-in-docker-container) in StackOverflow. But maybe there's something basic I'm missing?

I have a simple NRepl server running in a docker container. But I can't connect to that NRepl process.

My `docker-compose.yml` looks something like this.
```
version: '3'
services:
  foo:
    ports:
      - ${NREPL_PORT:-7001}:7001
```

But I consistently get an error when trying to connect from outside of docker.
```
λ lein repl :connect localhost:7001
Connecting to nREPL at localhost:7001
SocketException The transport's socket appears to have lost its connection to the nREPL server
        nrepl.transport/bencode/fn--9182/fn--9183 (transport.clj:108)
        nrepl.transport/bencode/fn--9182 (transport.clj:108)
        nrepl.transport/fn-transport/fn--9150 (transport.clj:55)
        clojure.core/binding-conveyor-fn/fn--5739 (core.clj:2030)
        java.util.concurrent.FutureTask.run (FutureTask.java:266)
        java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1142)
        java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:617)
        java.lang.Thread.run (Thread.java:745)
```

I've tried to listen on these addresses, but I get the same error every time.
```
  "0.0.0.0"
  "::"
```

And on running, I check and have the expected ports open.
```
λ docker ps
CONTAINER ID    IMAGE      COMMAND       CREATED         STATUS         PORTS                     NAMES
4d39d81fba69    api_api    "lein run"    5 minutes ago   Up 5 minutes   0.0.0.0:7001->7001/tcp    api_api_1
```

**Comment by darwin** [comment]
Have your tried to run the container using [host network](https://docs.docker.com/network/host/) directly? In docker-compose you should use `network_mode: "host"` under `foo` key.

I wonder if something like this is going on: https://stackoverflow.com/a/43528819/84283

**Comment by twashing** [comment]
@darwin Apologies, it looks like the process was dying not too long after it launched. When my code tries to do A), the error in B) pops up. And this is only happening when running in docker. Launching an nrepl server works on my host machine.

I tried and failed to troubleshoot with my attempts in C). So I'm not sure how to get around this problem.

A)
```
(nrepl.server/start-server :bind "::" :port 7001)
```

B)
```
Caused by: java.net.SocketException: Protocol family unavailable
    at java.net.PlainSocketImpl.socketBind(Native Method)
    at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:387)
    at java.net.ServerSocket.bind(ServerSocket.java:375)
    at java.net.ServerSocket.bind(ServerSocket.java:329)
    at nrepl.server$start_server.invokeStatic(server.clj:128)
    at nrepl.server$start_server.doInvoke(server.clj:96)
    at clojure.lang.RestFn.invoke(RestFn.java:457)
    at beacon.state.nrepl$eval45158$fn__45159.invoke(nrepl.clj:7)
    at mount.core$record_BANG_.invokeStatic(core.cljc:86)
    at mount.core$record_BANG_.invoke(core.cljc:85)
    at mount.core$up$fn__12135.invoke(core.cljc:93)
```

C)
```
# At invocation (bash)
java -Djava.net.preferIPv4Stack=true -Djava.net.preferIPv4Addresses=true ...

# In Clojure
(System/setProperty "java.net.preferIPv4Stack" "true")
(System/setProperty "java.net.preferIPv4Addresses" "true")
```

**Comment by darwin** [comment]
It would be great if you could produce a minimal repro dockerfile. I would try it here on my macOS or Ubuntu system.

In general I can just say that calling `nrepl.server/start-server`[1] inside docker always worked for me. But I never tried to connect to it from host machine.

[1] https://github.com/binaryage/dirac/blob/master/test/src/test_lib/dirac/test_lib/nrepl_server_helpers.clj#L26

**Comment by twashing** [comment]
@darwin Ok this helps. Because I created a micro project, which you can unzip and run with `docker-compose up`. And with project `foo` I can connect to it from host machine.

So there's some voodoo in my real project that's stopping stuff. Sigh :)
[foo.zip](https://github.com/nrepl/nrepl/files/4073469/foo.zip)

**Comment by darwin** [comment]
Ok, good, you are getting closer. But I don't have to test it until you have a minimal reproducible case.

**Comment by twashing** [comment]
Correct. I got it working. There was something weird going on with the routing tables between my host and docker. Everything's good now. 

Thanks for looking into it.
