### ISSUE TITLE
nrepl.core-test/sideloader-test fails sporadically

### ISSUE THREAD

**Issue by eerohele** [nrepl/nrepl#200]
See e.g. [job 2250](https://app.circleci.com/pipelines/github/nrepl/nrepl/155/workflows/d374a9ce-d5f1-4147-8b2b-cf0de0dfc1b9/jobs/2250/steps).

**Comment by bbatsov** [comment]
@shen-tian Can you take a look into this?

**Comment by eerohele** [comment]
Hopefully fixed via #213.
