### ISSUE TITLE
Completion candidate list can contain duplicate values

### ISSUE THREAD

**Issue by eerohele** [nrepl/nrepl#201]
## Expected behavior

Completion candidate list doesn't contain duplicate values.

## Actual behavior

Completion candidate list contains duplicate values.

## Steps to reproduce the problem

```clojure
=> (completions "String/v")
({:candidate "String/valueOf", :type :static-method}
 {:candidate "String/valueOf", :type :static-method}
 {:candidate "String/valueOf", :type :static-method}
 {:candidate "String/valueOf", :type :static-method}
 {:candidate "String/valueOf", :type :static-method}
 {:candidate "String/valueOf", :type :static-method}
 {:candidate "String/valueOf", :type :static-method}
 {:candidate "String/valueOf", :type :static-method}
 {:candidate "String/valueOf", :type :static-method})
```

### Clojure version

1.10.0

### Java version

11

### Operating system

macOS

---

The easiest solution would be to `dedupe` the current return value of `nrepl.util.completion/completions`. Another possibility would be to use `sorted-set-by`, but I don't know whether the Bencode encoder will be able to handle that. I also don't know which is faster, or whether it even matters here.

I can create a PR if you want, but I'll be travelling for a while, so it might be a while before I get to it. Wanted to create an issue so that I don't forget.

**Comment by bbatsov** [comment]
Hmm, I recall I had seen this a while ago and supposedly I had added some uniqueness check somewhere. The Java completion code is currently just a copy of the legacy clojure-complete Java completion (minus 2-3 bugs) and I didn't try much to understand/improve it. 

> Another possibility would be to use sorted-set-by, but I don't know whether the Bencode encoder will be able to handle that.

Sets become just regular bencode dictionaries in the end. Still, it seems to me that we should actually find out what's causing those duplicates in the first place.

**Comment by eerohele** [comment]
>Hmm, I recall I had seen this a while ago and supposedly I had added some uniqueness check somewhere.

It looks like `ns-java-methods` calls `distinct`, so that might be it.

I think the issue is simply that `static-members` currently returns every overload of every static method (as with `String/valueOf`). Simply adding a `distinct` call (as with `ns-java-methods`) would probably be the simplest fix.
