### ISSUE TITLE
List of middleware requires a "," between them, space is failing

### ISSUE THREAD

**Issue by behrica** [nrepl/nrepl#203]
It took me quite some hours to figure out, that the comma between the list of  middlewares is **required**,
and it does not work with a **space**.

This works in a deps.edn file

``` 
...
...
:main-opts ["-m" "nrepl.cmdline"
                                   "-b" "0.0.0.0"
                                   "-p" "12345"
                                   "--middleware"
                                   "[refactor-nrepl.middleware/wrap-refactor,cider.nrepl/cider-middleware]"
                                   ]
```

while this fails:
```
...
... 
:main-opts ["-m" "nrepl.cmdline"
                                   "-b" "0.0.0.0"
                                   "-p" "12345"
                                   "--middleware"
                                   "[refactor-nrepl.middleware/wrap-refactor cider.nrepl/cider-middleware]"
                                   ]
```

I would have expected that the list of middlewares follow the normal clojure syntax, in which komma is considered whitespace.

The "error" in this case is as well not helpfull:

```
Execution error at nrepl.cmdline/parse-cli-values$fn (cmdline.clj:250).
EOF while reading

Full report at:
/tmp/clojure-9160228017090719565.edn
```

**Comment by bbatsov** [comment]
Hmm, that's weird. I guess it's going to be easy to fix that.

**Comment by SevereOverfl0w** [comment]
This is how deps.edn works, not a nrepl bug

**Comment by behrica** [comment]
> This is how deps.edn works, not a nrepl bug

Maybe just a question of documentation. I got "confused" by this line of the docu:

-m/--middleware MIDDLEWARE  A sequence of vars, representing middleware you wish to mix in to the nREPL handler.

**sequence of vars**   made me think that **valid clojure syntax for a sequence** is the right format for it, which would allow space or comma

**Comment by behrica** [comment]
I found a bug report about the same:

https://ask.clojure.org/index.php/9034/clj-m-works-from-shell-but-not-as-alias

and it was further discussed on clojure.core  : https://clojure.atlassian.net/browse/TDEPS-56

I would therefore accept it as is here.

But maybe you could add / change the docu and have an example with two middlewares in a deps.edn.

I seems to be only an issue, if alias are used, while on commandline it is ok.

Or maybe just change the help text to:

```
-m/--middleware MIDDLEWARE  A sequence of comma separated vars, representing middleware you wish to mix in to the nREPL handler.
```

**Comment by SevereOverfl0w** [comment]
The help text is correct. Deps can't handle spaces.
