### ISSUE TITLE
Syntax error occured with nREPL 0.8.0 and cider-nrepl on Java8

### ISSUE THREAD

**Issue by liquidz** [nrepl/nrepl#206]
Moved from https://github.com/clojure-emacs/orchard/issues/98

These changes may be the cause.
https://github.com/nrepl/nrepl/commit/c3ec4c6#diff-1b9ca3ef5a3a453d96b5f6c1b8c778a5L73-L138

@shen-tian Do you have a time to confirm?

## Expected behavior

`lein repl` will launch.

## Actual behavior

```
ERROR: Unhandled REPL handler exception processing message {:code (clojure.core/binding [clojure.core/*ns* (clojure.core/or (clojure.core/find-ns (clojure.core/symbol "reply.eval-mode
s.nrepl")) clojure.core/*ns*)] (set! *print-length* nil)), :id d9e84203-70ce-4144-8d6c-8c8aa8994446, :op eval, :session 71e6dc37-2c17-48a9-b70e-b42454c30d3d}
Syntax error compiling at (cider/nrepl/inlined_deps/orchard/v0v6v0/orchard/java/legacy_parser.clj:1:1).
```

Full error messages are here
https://gist.github.com/liquidz/6c2da4394b3a238947ad493c604e0d7a

## Steps to reproduce the problem

- create project
```sh
docker run --rm -it clojure:openjdk-8-lein bash
lein new foo
cd foo
```
- edit `project.clj`
```clojure
(defproject foo "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "EPL-2.0 OR GPL-2.0-or-later WITH Classpath-exception-2.0"
            :url "https://www.eclipse.org/legal/epl-2.0/"}
  :dependencies [[org.clojure/clojure "1.10.1"]
                 [nrepl "0.8.0"]]
  :plugins [[cider/cider-nrepl "0.25.3"]]
  :repl-options {:init-ns foo.core})
```
- run `lein repl`

### Clojure version

- 1.10.1

### Java version

- 1.8

### Operating system

- Debian (Docker image: clojure:openjdk-8-lein)
- macOS Catalina

**Comment by shen-tian** [comment]
Hey. Will have a go at reproducing..

**Comment by shen-tian** [comment]
I've had a look at the issue. Can reproduce, as described, and the problem is most likely introduced in the commit you linked to.

As to why, I think it's failing to load `com.sun.javadoc.ClassDoc`, which is in `tools.jar` in Java 8, based on the discussion [here](https://github.com/clojure-emacs/orchard/issues/50). My guess is that `clojure.lang.Compiler/LOADER` had access to it, but the contextual class loader does not 🤷 .

Let me see if I can pull together a fix..

**Comment by liquidz** [comment]
Thanks for your confirmation!

**Comment by shen-tian** [comment]
It looks like this is a bit of a clash between 

- how orchard adds `tools.jar` onto the classpath, using some heuristics and adding it using dynapath... 
- and how we fixed #113, which has to do with supporting how Pomegranate modified the classpath, which is by ensuring `clojure.lang.Compiler/LOADER` shared a common ancestor as the Contextual ClassLoader.

No immediate solutions comes to mind, I'm happy to do some more research and see, but help is also welcome, especially from anyone with ideas on how dynamic classloaders works.

**Comment by bbatsov** [comment]
> how orchard adds tools.jar onto the classpath, using some heuristics and adding it using dynapath...

One idea that comes to mind is to drop the usage of dynapath in Orchard. If we can replace this with another approach that'd be ideal IMO, as there's also https://github.com/clojure-emacs/orchard/issues/20 Alternatively we can have either nREPL add `tools.jar` to the classpath or have clients do this explicitly. Not sure about the best approach, as I'm far from an expert in dynamic classloaders. Maybe @SevereOverfl0w would have some ideas.

**Comment by jwr** [comment]
Just to confirm, I ran into the same problem while updating dependencies in a large project. Switching from nrepl 0.7.0 to 0.8.0 caused the problem to appear.

I'm switching back to 0.7.0 for now.
