### ISSUE TITLE
Error starting repl with Boot in Windows

### ISSUE THREAD

**Issue by ahwatts** [nrepl/nrepl#209]
Starting a REPL with `boot repl` using `nREPL` 0.8 throws a `NullPointerException` on startup, though it doesn't crash the process entirely. The process appears to be unusable, however.

This looks like it's the same as https://github.com/clojure-emacs/cider/issues/2893 , but I'm filing it here because I can reproduce it without CIDER involved at all.

This works fine if I set the `nREPL` dependency to 0.7.0 or 0.6.0.

# Expected behavior

`boot repl` should start a REPL.

## Actual behavior

```
C:\Users\Andrew Watts> boot -d nrepl:0.8.0 repl
[WARNING] No nREPL middleware descriptor in metadata of null, see nrepl.middleware/set-descriptor!
nREPL server started on port 50607 on host 127.0.0.1 - nrepl://127.0.0.1:50607
ERROR: Unhandled REPL handler exception processing message {:id 2995ad98-b1e6-479c-af71-244ea844862c, :op clone}
java.lang.NullPointerException
        at nrepl.middleware.dynamic_loader$wrap_dynamic_loader$fn__4663.invoke(dynamic_loader.clj:97)
        at nrepl.middleware$wrap_conj_descriptor$fn__4162.invoke(middleware.clj:16)
        at nrepl.server$default_handler$fn__5089.invoke(server.clj:130)
        at nrepl.server$handle_STAR_.invokeStatic(server.clj:22)
        at nrepl.server$handle_STAR_.invoke(server.clj:19)
        at nrepl.server$handle$fn__5060.invoke(server.clj:39)
        at clojure.core$binding_conveyor_fn$fn__5754.invoke(core.clj:2030)
        at clojure.lang.AFn.call(AFn.java:18)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

## Steps to reproduce the problem

Run `boot -d nrepl:0.8.0 repl` in a directory without a `build.boot` or `boot.properties` file.

### Clojure version

```
C:\Users\Andrew Watts> boot -V
#http://boot-clj.com
#Sat Aug 29 01:22:24 EDT 2020
BOOT_CLOJURE_NAME=org.clojure/clojure
BOOT_CLOJURE_VERSION=1.10.1
BOOT_VERSION=2.8.3
```

### Java version

```
C:\Users\Andrew Watts> java -version
java version "1.8.0_211"
Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.211-b12, mixed mode)
```

### Operating system

```
Microsoft Windows [Version 10.0.19041.450]
(c) 2020 Microsoft Corporation. All rights reserved.
```

**Comment by shen-tian** [comment]
Thank @ahwatts. Let me dig up a Windows machine and have a look this week.

**Comment by gsuzor91** [comment]
[clojure-emacs/cider#2893](https://github.com/clojure-emacs/cider/issues/2893) was closed stating that `nrepl 0.8.1` corrected it. As @ahwatts previously mentioned, `cider#2893` looks to be the same as this issue, but reproduced here with the simpler `boot -d nrepl:0.8.0 repl`.

However, if I try `boot -d nrepl:0.8.1` I still get a `NullPointerExcepion` as originally reported above.
`Windows 10 Pro 2004 (19041.450)` `Boot 2.8.3` `AdoptOpenJDK jdk-8.0.265.01-openj9`

I also did a quick test with `AdoptOpenJDK 11` with the same results, so this issue doesn't seem to be specific to `JDK 8`.
_(Side note: I had to edit the registry to get `boot` to recognize `AdoptOpenJDK 11`, but that's a different topic.)_

**Comment by bbatsov** [comment]
I guess I was too optimistic in my assumption then. I'll reopen the CIDER ticket.

**Comment by alexander-yakushev** [comment]
Given that Boot will is abandoned and will never update its nREPL dependency even if this is fixed in some version, I think this can be closed as wontfix.

**Comment by bbatsov** [comment]
Yeah, that's fair.

**Comment by ahwatts** [comment]
I've long since switched to deps.edn, so this is moot for me now. (Boot is moot!)
