### ISSUE TITLE
Run CI on OpenJDK 15

### ISSUE THREAD

**Issue by bbatsov** [nrepl/nrepl#223]
Mostly a matter of figuring out what image to use for the build as it seems there's no `openjdk-15-lein-2.9.1`.

**Comment by sudorock** [comment]
There is `clojure:openjdk-15-lein-2.9.5`, is lein required to be `2.9.1`?

**Comment by bbatsov** [comment]
Nope, newer is better.

**Comment by bbatsov** [comment]
That's already solved.
