### ISSUE TITLE
ClassCastException raised when connecting to nREPL server via nrepl+unix

### ISSUE THREAD

**Issue by athos** [nrepl/nrepl#245]
I'm messing with nrepl/nrepl 0.9.0-beta2 to [make my nREPL client support the new `nrepl+unix` connection](https://github.com/athos/trenchman/pull/8).

When starting up an nREPL server on JVM 16 with the following command:

```sh
$ clj -Sdeps '{:deps {nrepl/nrepl {:mvn/version "0.9.0-beta2"}}}' -M -m nrepl.cmdline -s nreplsock
```

And then connecting to it via `nrepl+unix`, I found the server raised an error like the following:

```
ERROR: Unhandled REPL handler exception processing message {:id init, :op clone}
java.lang.ClassCastException: class nrepl.socket.BufferedOutputChannel cannot be cast to class java.io.OutputStream (nrepl.socket.BufferedOutputChannel is in unnamed module of loader clojure.lang.DynamicClassLoader @3af356f; java.io.OutputStream is in module java.base of loader 'bootstrap')
        at nrepl.transport$safe_write_bencode.invokeStatic(transport.clj:112)
        at nrepl.transport$safe_write_bencode.invoke(transport.clj:104)
        at nrepl.transport$bencode$fn__673.invoke(transport.clj:131)
        at nrepl.transport.FnTransport.send(transport.clj:35)
        at nrepl.middleware.session$register_session.invokeStatic(session.clj:240)
        at nrepl.middleware.session$register_session.invoke(session.clj:232)
        at nrepl.middleware.session$session$fn__1334.invoke(session.clj:304)
        at nrepl.middleware$wrap_conj_descriptor$fn__899.invoke(middleware.clj:16)
        at nrepl.server$default_handler$fn__1884.invoke(server.clj:141)
        at nrepl.server$handle_STAR_.invokeStatic(server.clj:24)
        at nrepl.server$handle_STAR_.invoke(server.clj:21)
        at nrepl.server$handle$fn__1852.invoke(server.clj:41)
        at clojure.core$binding_conveyor_fn$fn__5772.invoke(core.clj:2034)
        at clojure.lang.AFn.call(AFn.java:18)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:831)
```

On the other hand, if I start up the server with `junixsocket` added as a dependency, no such error will occur even after the connection is established:

```sh
$ clj -J-Dnrepl.test.junixsocket -Sdeps '{:deps {nrepl/nrepl {:mvn/version "0.9.0-beta2"} com.kohlschutter.junixsocket/junixsocket-core {:mvn/version "2.3.4"}}}' -M -m nrepl.cmdline -s nreplsock
```

While I was looking into the codebase as tracking the stacktrace, I found that [`SocketChannel`'s implementation of `buffered-output` returns `BufferedOutputChannel`](https://github.com/nrepl/nrepl/blob/366cf7ca596f9418d96bb5d3d16f16476cb15649/src/clojure/nrepl/socket.clj#L226), not `BufferedOutputStream` despite the docstring for `buffered-output` says it returns [a subset of `BufferedOutputStream`](https://github.com/nrepl/nrepl/blob/366cf7ca596f9418d96bb5d3d16f16476cb15649/src/clojure/nrepl/socket.clj#L222). Is this intended? Or am I missing something?

## Expected behavior
That an nREPL server running on JVM >= 16 accepts an `nrepl+unix` connection with no error.

## Actual behavior
`ClassCastException` will be thrown when connecting via `nrepl+unix` to an nREPL server on JVM 16.

## Steps to reproduce the problem
As described above.

### Clojure version

1.10.3

### Java version

```
openjdk version "16" 2021-03-16
OpenJDK Runtime Environment AdoptOpenJDK (build 16+36)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 16+36, mixed mode, sharing)
```

### Operating system

macOS Big Sur 11.5.2

**Comment by bbatsov** [comment]
@rlbdv Can you look into this?

**Comment by rlbdv** [comment]
Bozhidar Batsov ***@***.***> writes:

> @rlbdv Can you look into this?

Certainly - though it might not be until later this week(end).

**Comment by bbatsov** [comment]
No rush.

**Comment by rlbdv** [comment]
Bozhidar Batsov ***@***.***> writes:

> @rlbdv ping :-) That's probably the only ticket I'm concerned about before cutting nREPL 0.9. 

Starting to look...

**Comment by bbatsov** [comment]
Thanks!

**Comment by rlbdv** [comment]
Just noticed something else is different with jdk 16 support, i.e. this, which has worked and does work fine with junixsocket (at least) just hangs with jdk16: `echo 'd4:code7:(+ 2 2)2:op4:evale' | nc -U nreplsock` when connecting to
```sh
lein with-profile +junixsocket run -m nrepl.cmdline -s nreplsock
```
Don't know if the issues are related, but I'm finally investigating.

**Comment by rlbdv** [comment]
@athos how were you connecting when you saw the initial crash?

**Comment by rlbdv** [comment]
(I did see your detailed description of the underlying issue, and am looking in to it, but also wanted to see how you were producing the error.)

**Comment by rlbdv** [comment]
Oh, you were probably using your client.

**Comment by rlbdv** [comment]
OK, mystery partially solved - it looks like the two things are related.  Removing that incorrect type annotation allows the `echo ... | nc ...` to work fine.  Presumably the same exception was being thrown, but (no idea why yet) not being shown by `lein run ...` or `lein trampoline run ...`.

In any case, I'll try to come up with a fix for the types, assuming we still have to have that annotation to avoid reflection.

**Comment by bbatsov** [comment]
I guess we can just remove this annotation if its hard to find a solution with it (or another annotation) in place. For me it's way more important for the code to work properly than to avoid some reflection warning.

**Comment by rlbdv** [comment]
I think I may have a clean fix, and I'm wondering if I might have meant to do this in the first place and wandered off (cf. `socket/Writable`).  May have a pr soon, though I'm hitting an eastwood error in session.clj on the current branch.

**Comment by rlbdv** [comment]
Oh, and I'm not usually worried about every reflection warning, but I thought that was being enforced now in CI.

**Comment by rlbdv** [comment]
This one, for reference:
> == Linting nrepl.middleware.session ==
> src/clojure/nrepl/middleware/session.clj:44:3: wrong-tag {:kind :clj-1232}: Tag: DynamicClassLoader
for return type of function on arg vector: [cl] should be fully qualified Java class name, or else it may cause exception if used from another namespace. This is only an issue for Clojure 1.7 and earlier. Clojure 1.8 fixes it (CLJ-1232 https://dev.clojure.org/jira/browse/CLJ-1232).

**Comment by rlbdv** [comment]
https://github.com/nrepl/nrepl/pull/255 should fix the [DynamicClassLoader issue](https://github.com/nrepl/nrepl/issues/245#issuecomment-962685978) too.

**Comment by athos** [comment]
@rlbdv Thank you for fixing this! I've confirmed that my nREPL client also successfully connects to the nREPL server running on JVM 17 via `nrepl+unix`.

**Comment by bbatsov** [comment]
0.9.0-beta4 is out with the fix.
