### ISSUE TITLE
0.3.0 java classes are incompatible with Java 8 and 9

### ISSUE THREAD

**Issue by ajoberstar** [nrepl/nREPL#26]
Using nREPL in Java 8, I get the following error. It appears the Java classes in 0.3.0 were compiled for Java 10. Is this intentional or should it still be compatible with 8?

```
java.lang.UnsupportedClassVersionError: clojure/tools/nrepl/StdOutBuffer has been compiled by a more recent version of the Java Runtime (class file version 54.0), this version of the Java Runtime only recognizes class file versions up to 52.0, compiling:(clojure/tools/nrepl/middleware/session.clj:31:13)
```

**Comment by bbatsov** [comment]
@ajoberstar Hmm, seems that's an oversight of mine. I'll have to check the lein settings, as I assumed the default was something less aggressive.

**Comment by bbatsov** [comment]
Check out 0.3.1. I've rebuild it for Java 8.

**Comment by ajoberstar** [comment]
Good to go. Thanks for the quick fix!
