### ISSUE TITLE
project.clj on the main branch is still set to 0.9.0

### ISSUE THREAD

**Issue by rlbdv** [nrepl/nrepl#280]
I imagined that might be an oversight.

**Comment by bbatsov** [comment]
Not exactly. I haven't decided yet what the next version should be (1.0, 0.9.1 or 0.10). I'm leaning towards 1.0 currently and probably the bigger improvements brought up [here](https://github.com/nrepl/nrepl/discussions/275) will happen in 1.x versions.

**Comment by rlbdv** [comment]
Hmm, wonder if you might still want to consider changing it to at least `0.9.1-SNAPSHOT` for now, so that people who need to work with/test the branch (was my case while working on filesystem socket support for `lein repl`), won't accidentally try to push 0.9.0 on `lein install`.
