### ISSUE TITLE
Create a simple logo for the project (and this org)

### ISSUE THREAD

**Issue by bbatsov** [nrepl/nrepl#30]
The GitHub org is looking a bit pale without a logo. :-) It'd be nice if the project had some basic logo, but I'll need some help with that, as I'm a complete zero in the design department. :-)

**Comment by andrerichards** [comment]
I threw this together.

<img width="437" alt="nrepl" src="https://user-images.githubusercontent.com/1530731/40285353-e3805662-5c92-11e8-8f75-f57b9d21adc3.png">

**Comment by andrerichards** [comment]
Here is one that is same width & height

<img width="440" alt="nrepl" src="https://user-images.githubusercontent.com/1530731/40285470-275f4ff4-5c94-11e8-9e90-bfb59c264965.png">

**Comment by bbatsov** [comment]
Thanks! Just a bit of feedback from me:

* What's the meaning behind the design? :-)
* How is this going to look as a favicon? That's something I really like about the CIDER logo - the mug-like element there is the natural favicon. Perhaps we can style some of the letters in nREPL somehow? E.g. the E could look like a "server" somehow. 
* I wonder if we can't put some REPL reference in there like `> nREPL`.

**Comment by martinklepsch** [comment]
Throwing in a few ideas: 

<img width="599" alt="screen shot 2018-05-28 at 14 57 12" src="https://user-images.githubusercontent.com/97496/40615565-90e0cec8-6287-11e8-9a56-87b2e30a2c67.png">

<img width="411" alt="screen shot 2018-05-28 at 14 57 42" src="https://user-images.githubusercontent.com/97496/40615568-93dad650-6287-11e8-8c4e-54f7542e3c92.png">

<img width="466" alt="screen shot 2018-05-28 at 14 57 22" src="https://user-images.githubusercontent.com/97496/40615570-96324dca-6287-11e8-940d-817b2f7ad744.png">

**Comment by bbatsov** [comment]
@martinklepsch Nice!

I like the second and the third the best, as I can imagine how they can also be used for icons (for instance). What is the second shape in the 3rd logo supposed to mean? I assume that's the loop, but It blends a bit with the background now and someone might think it's something related to the N letter.

**Comment by martinklepsch** [comment]
It's the loop yeah, could be made more explicit. A still fairly subtle variant: 

<img width="399" alt="screen shot 2018-05-28 at 16 01 50" src="https://user-images.githubusercontent.com/97496/40618047-8703a318-6290-11e8-942c-0e8364d08a16.png">

**Comment by martinklepsch** [comment]
FWIW I really liked the protocol idea from the first suggestion but am also not convinced about the current look. If you have ideas for that, let me know :)

**Comment by bbatsov** [comment]
Yeah, that's better. The protocol idea is cool, but I simply don't see how this can be converted to the square version of a logo you need for things like icons. (and perhaps there should be some parens around it as a nod to Lisp). :-)

**Comment by andrerichards** [comment]
> Thanks! Just a bit of feedback from me:
> What's the meaning behind the design? :-)

Basically just a continuous loop

> How is this going to look as a favicon? That's something I really like about the CIDER logo - the mug-like element there is the natural favicon. Perhaps we can style some of the letters in nREPL somehow? E.g. the E could look like a "server" somehow.
I wonder if we can't put some REPL reference in there like > nREPL

I'm afraid I'm not really a designer, just downloaded some free software and threw together something. If you want specific designs like E that looks like server, I'm not the right person :-)

I'm glad you received some other options as well.

**Comment by luckypunk** [comment]
![nrepl2](https://user-images.githubusercontent.com/25934113/47784248-4f4fb980-dd05-11e8-8e1f-8f4174116bcd.png)

**Comment by tonsky** [comment]
I might also have something to propose
![nrepl](https://user-images.githubusercontent.com/285292/47808713-07a24f80-dd50-11e8-9aa8-ab60f91f3763.png)

**Comment by bbatsov** [comment]
@tonsky I believe we have a winner! I love it!

**Comment by bbatsov** [comment]
Can I ask you to export this in a few sizes + some favicons as we did for the CIDER logo? (https://github.com/clojure-emacs/cider/tree/master/logo)

**Comment by tonsky** [comment]
Sure will do tomorrow

**Comment by bbatsov** [comment]
Thanks! 🙇

**Comment by bbatsov** [comment]
Btw, a designer friend of mine gave a bit of feedback that seems reasonable, so I'll pass it along. He suggested to include `n/N` also in the black text, as according to him it was customary to spell the entire name out of a project/company. He also mention that this would make it easier to vertically align the logo symbol and the text. I'm no expert, but I decided to share this in case you want to check if looks better this way. At any rate - it's a good idea to have vertical and horizontal variant of the logo.
