### ISSUE TITLE
[Request] New release + Docs update

### ISSUE THREAD

**Issue by p4v4n** [nrepl/nrepl#301]
Mainly interested in the updated documentation since the last release.

- [ ] New (Snapshot?) Release
- [ ] Update Docs (cljdoc + website)

**Comment by bbatsov** [comment]
Yeah, I guess we should do both. Things have been quiet on the TSL front, which is the main new feature in the next nREPL release, so we might do a final release soon as well.

**Comment by bbatsov** [comment]
There's one open ticket I'd like us to resolve before cutting a release https://github.com/nrepl/nrepl/pull/288

**Comment by bbatsov** [comment]
Done.
