### ISSUE TITLE
Fix bugged (TLS) accept loop

### ISSUE THREAD

**Issue by ivarref** [nrepl/nrepl#306]
Placeholder for fixing TLS flaky test(s).

Adding an issue for this, re comments at https://github.com/nrepl/nrepl/pull/304 and https://github.com/nrepl/nrepl/pull/305

I have not been able to reproduce this locally, but I do believe I've found some incorrectness that could lead to a server that is no longer accepting connections, i.e. the accept loop exits. It's pushed at https://github.com/nrepl/nrepl/compare/master...ivarref:nrepl:master

I'm using java version:
```bash
$ java -version
openjdk version "20-ea" 2023-03-21
OpenJDK Runtime Environment (build 20-ea+34-2340)
OpenJDK 64-Bit Server VM (build 20-ea+34-2340, mixed mode, sharing)
```

Some open questions:

How can we debug this in CI?

What test(s) is it that deadlock? Or is the whole suite just taking more than 10 minutes?

Regards

**Comment by bbatsov** [comment]
Fixed by #307
