### ISSUE TITLE
Ensure that the Clojure version is supported

### ISSUE THREAD

**Issue by vemv** [nrepl/nrepl#308]
Given that e.g. cider-nrepl [can fail badly](https://clojurians.slack.com/archives/C0617A8PQ/p1705170410908489) on older Clojures (including timed out nrepl ops and a frozen Emacs), and considering that the supported Clojure versions [got bumped recently](https://github.com/nrepl/nrepl/pull/305), I'd consider ensuring at runtime that the effective Clojure version is supported.

There are a few approaches that I could see working, e.g.

* Perform a `System/exit` eagerly if the detected version does not meet the minimum
* Introduce a middleware that wraps the response with `err`, based on the same condition
  * an err response can be more cleanly detected client-side.
* Perform the check in the most important ops e.g. `clone`
  * I'd prefer this one over middleware - less room for error (e.g. what if the `err` gets overriden)

Thoughts?

**Comment by bbatsov** [comment]
I'm just not sure how adding this in nREPL with help `cider-nrepl`, as they target different Clojure versions. 

> Perform a System/exit eagerly if the detected version does not meet the minimum

Seems like the simplest solution. I thought we were doing something similar in `cider-nrepl`, at least for the Lein plugin.

**Comment by vemv** [comment]
> I'm just not sure how adding this in nREPL with help cider-nrepl, as they target different Clojure versions.

Yes they're slightly different, although 1.9 also became [partially unsupported](https://github.com/clojure-emacs/cider-nrepl/commit/c80f47c231acce5d6508c56e7d5868e4c726704c) in cider-nrepl.

I reckon that sooner or later there will be no difference.

> the Lein plugin

There's a `warn`, yes. Given that you're OK with it, maybe we can just perform a plain `System/exit` nearby [these other side effects](https://github.com/clojure-emacs/cider-nrepl/blob/c80f47c231acce5d6508c56e7d5868e4c726704c/src/cider/nrepl.clj#L28-L29) - for all platforms.

**Comment by bbatsov** [comment]
> I reckon that sooner or later there will be no difference.

I'm not so sure about that, as nREPL is supposed to target older Clojure versions. I bumped its target version only once (from 1.2 to 1.7) since I became its maintainer and I recall a few people were complaining that running `lein repl` in older projects broke for them, so the required version has stayed at 1.7 ever since. For Cursive it's also important that nREPL supports relatively old Clojure (it used to target Clojure 1.7, I'm not sure if that's still the case). 

With `cider-nrepl` we have a lot more leeway, as it's not some foundational library.

**Comment by vemv** [comment]
My understanding is that with https://github.com/nrepl/nrepl/pull/305 changes.

But anyway, happy to go for the simplest thing, in cider-nrepl.

**Comment by bbatsov** [comment]
Now the older Clojure versions are tested only with JDK 8, as it's unlikely anyone would be using them with newer JDKs. 
For me it's always convenient to support fewer versions, but I try to be accommodating to as many of our users as possible. I'm guessing we'll be stuck with supporting 1.7 and 1.8 until there are still people using JDK 8.

**Comment by alexander-yakushev** [comment]
I really don't like `System/exit` approach from a library – I don't think any library has an authority to forcefully kill the application process. Throwing an exception when the namespace loads or in primary entrypoints (`start-server`) is a softer solution that achieves the same.

**Comment by bbatsov** [comment]
I'm inclined to agree with you. In general, given that nREPL supports ancient versions of Clojure I'm not sure that's even a problem we need to solve. At least it's not a particularly important problem.
