### ISSUE TITLE
Modernize bencode implementation

### ISSUE THREAD

**Issue by alexander-yakushev** [nrepl/nrepl#322]
Before trying to address #285 I'd like to ask if there's a desire/will to update the bencode implementation in nREPL (and github.com/nrepl/encode). From the various old-style `#^{:private true}` metadata I can infer that it was written a long time ago and haven't been touched ever since. I see a few potential performance improvements in that implementation and much space for modernization. But I understand that bencode is the cornerstone of nREPL and it might be scary to touch it. How confident are you in tests for it, @bbatsov?

**Comment by bbatsov** [comment]
> How confident are you in tests for it, @bbatsov?

Quite confident. The implementation basically hasn't been touched in over 10 years (it targeted Clojure 1.1 or 1.2 if I recall correctly), but I know that no codebase is perfect and suggestions for improvements are always welcome. Performance improvements would be particularly welcome.

**Comment by alexander-yakushev** [comment]
Complete in #323.
