### ISSUE TITLE
Replace usage of clojure.main/repl with custom REPL implementation

### ISSUE THREAD

**Issue by alexander-yakushev** [nrepl/nrepl#330]
`clojure.main/repl` has been causing quite a few woes, especially with its classloader mismanagement (#327). Given that it is:

1. Pretty simple and short in its implementation to be adopted;
2. Contains logic that is fundamental to nREPL and is something that nREPL would like to control more;
3. Is already somewhat incompatible with what nREPL does (`clojure.main/repl` at its core has a streaming API, nREPL uses it to emulate message-oriented logic).

It makes sense to take over that code, repurpose and fit it better to our needs.

**Comment by bbatsov** [comment]
That would be really great to address, as we had to work around quite a few issues with `clojure.main/repl`. You probably remember that Chas himself regretted the choice of `clojure.main/repl` on a few occasions. I'll add here related tickets & additional discussions (if I manage to recall where they happened).

**Comment by alexander-yakushev** [comment]
Closed by #339.
