### ISSUE TITLE
Make threading usage more organized

### ISSUE THREAD

**Issue by alexander-yakushev** [nrepl/nrepl#332]
Currently, nREPL is qiute haphazard about how it uses multi-threading. While the session middleware has a dedicated named threadpool and carefully manages session threads with it, in other places (reading/writing over the transport, killing stuck threads, etc.) a generic `noisy-future` function is used. This has two problems:

1. Putting that work on the Futures executor obscures what nREPL related-code is running/waiting and where.
2. By touching the Clojure futures, nREPL initializes their threadpool and potentially prevents the application from shutting down (since Future threads are non-daemon ones).

Ideally, we want all nREPL threading to be neatly subdivided into threadpools with clear separation what happens where.

**Comment by bbatsov** [comment]
Yeah, I totally agree. The code there hasn't seen much changes since deciding to map evaluation threads to sessions (https://github.com/nrepl/nrepl/pull/98 and https://github.com/nrepl/nrepl/pull/127) and we definitely haven't thought much about the bigger picture.

**Comment by alexander-yakushev** [comment]
Fixed in #345.
