### ISSUE TITLE
State of sideloading and middleware injection?

### ISSUE THREAD

**Issue by alexander-yakushev** [nrepl/nrepl#333]
What is the current stance on these features? Obviously, they are not going anywhere, but is there any current interest in them? Do any ecosystem tools started using those and depend on them? Is there will and interest to develop, improve, and eventually converge them with the default middleware setup? I'm trying to understand if these features were done and now fulfill their purpose or they were left in semi-baked experimental state and never took off.

**Comment by bbatsov** [comment]
I know that only iced-vim is currently fully supporting sideloading at the client side. Not sure if they are actually using it for something. I still think that could be an useful way for editors to load some libraries or middleware on the fly, which would be nice for people using `cider-connect` or loading CIDER plugins on demand.

The way I see there are 2 main problems today:

1. It's kind of hard to use this, as you can't just instruct it to load some jar
2. Potentially `add-lib` can provide a simpler way to do this (as discussed here https://github.com/nrepl/nrepl/pull/246)

>  they were left in semi-baked experimental state and never took off.

That's the current state of affairs for sure. My initial intention was to make it easier for clients to use nREPL without having to rely on a lot of external middleware. E.g. they'd just sideload some Clojure library (e.g. for profiling) and eval code from it directly. Then we extended the scope to sideloading middleware, but never got both features to a state in which they were easy to use and somewhere there the work got stuck.

**Comment by bbatsov** [comment]
Actually, this issue best summarizes the state of affairs https://github.com/clojure-emacs/cider/issues/3037 Basically, we were pretty close to making it possible to sideload CIDER's middleware, but didn't get to the finish line.

**Comment by alexander-yakushev** [comment]
Thank you for the context!

I can't help but wonder if sideloading middleware is a tradeoff worth doing overall. I can clearly see the benefit for the user – not having to pre-specify the middleware dependencies like cider-nrepl and the middleware itself is useful. But for the developers, it seems to be adding a hell lot of extra complexity and points of failure. Currently, we are at least sure (and can check) that cider-nrepl dependency is on the classpath, and the real classpath, not some artificial emulation of it. If the wrong thing is loaded, again, this can be debugged using the usual methods that the user already knows from regular Clojure dependency management.

Speaking subjectively here, I as a user would prefer the current way of loading things, and maybe would appreciate an option to sideload for a remote prod REPL scenario. But I personally don't find value in sideloading for a local REPL that I have full control of.

Anyway, thanks again, I was wondering if this part of nREPL can be left as is for now, or if there is a desire to unearth and finish it.

**Comment by bbatsov** [comment]
The inspiration from the sideloading came from Unrepl and the idea that each client would easily create a "custom" REPL that would sideload whatever the client needs, instead of having one standard REPL for all clients. To me this seemed quite interesting in the context of many people complaining that cider-nrepl was too complex/slow/whatever, and I saw it as some potentially lighter/simpler alternative to our traditional approach. 

But clearly I also wasn't motivated to push this idea much, as I find it easier to use nREPL ops than raw evals for standard REPL interactions. The idea to use sideloading for middleware came later, and I thought this also had the potential to simplify some things internally (at the cost of great complexity in nREPL, of course). I definitely think we should finish this or remove it, but perhaps we can discuss it after doing some "State of CIDER" survey and checking if someone actually uses it with CIDER.

**Comment by bbatsov** [comment]
@plexus, if you get a moment, feel free to share your perspective as well given that you probably played with the sideloader functionality the most. 

cc @PEZ @cmf @liquidz

**Comment by cursive-ide** [comment]
I don't have strong feelings about this, I never implemented it in Cursive and no-one asked for it either. That said, I've actually had a couple of cases myself recently where it would have been useful. But in general, in Cursive I've philosophically steered away from middleware and just used eval - that approach has served me well and I plan to stick with it. My short-term plans including adding support for add-lib, which seems more generally useful, although it's a somewhat different use case.

**Comment by bbatsov** [comment]
> But in general, in Cursive I've philosophically steered away from middleware and just used eval - that approach has served me well and I plan to stick with it.

@cursive-ide Just to be clear - the original idea of the sideloader was to support exactly your use-case, not dynamic middleware loading. Basically you bundle some Clojure/Java libraries with your client and the sideloader will load them on-the-fly when code from them gets required by some evaluation.  The sideloading of middleware is just an extension of the core sideloading functionality.

**Comment by plexus** [comment]
> @plexus, if you get a moment, feel free to share your perspective

It's been a while... from what I remember I think all the pieces are basically there, but we're missing the orchestration to piece it all together and make it generally useful (which is a client concern). It does add significant complexity, and also overhead. It involves adding an extra classloader that fulfills requests via nrepl messages to the client, that's a pretty slow mechanism compared to pulling stuff directly off disk.

As @bbatsov said, the goal was to weaken the demands a given client puts upon the nREPL server. Any client would be able to connect to a "vanilla" nREPL server, and upgrade/sideload anything it needs. Right now starting a REPL without some kind of "jack-in" functionality inside the editor can be a PITA, this would fix that. See also [launchpad](https://github.com/lambdaisland/launchpad), which I created in part to solve this PITA.

There are two sides to this: allowing the nREPL client to "serve up" namespaces and other resources to the application process, and allowing the middleware stack to be manipulated at runtime. The first part is really only necessary if you assume the client and server don't have access to the same disk. Which we kind of have to assume being a network protocol, but in practice most of the time they do share a disk, and then there are other mechanisms (add-lib, [lambdaisland/classpath](https://github.com/lambdaisland/classpath)) to make namespaces available for clojure to load.

So you could also imagine a client which uses one of those mechanisms to add whatever supporting namespaces or middleware they need to the classpath, and then load them and add them to the middleware stack. Either way CIDER has never gone the extra mile of actually implementing the orchestration needed to make that work (with sideloading or through classpath manipulation). It's a real question whether the benefits in this case outweigh the cost (developer/maintainer time, and performance hit).

**Comment by alexander-yakushev** [comment]
Could you please elaborate a bit more a little more on the performance hit part? I haven't looked deeply into it yet, but I would naively assume that if nREPL added a JAR to the topmost DynamicClassLoader via `.addURL` method (just like `add-lib` is doing), then the performance would be the same as if the JAR was on the classpath in the first place?

**Comment by alexander-yakushev** [comment]
Let me sideload the Slack thread here: https://clojurians.slack.com/archives/C04CAKAGADU/p1717505624333639

**Comment by alexander-yakushev** [comment]
Yes, I kinda see that in the code, but I never understood why this particular approach was taken vs. the `.addUrl` one.

**Comment by plexus** [comment]
Because it's a networked REPL, it might be on a different machine. Like I said that's not that common, but for this use case relevant I think, as people will often embed an nREPL server into their production apps, but not necessarily have things like the cider middleware included.

**Comment by alexander-yakushev** [comment]
I see that the sideloader requests a classfile from the client, which the client then sends to the server base64-encoded. Couldn't the client send the whole JAR in the same way?

**Comment by plexus** [comment]
It could, but I doubt it will be more efficient. You would save a bit because jar files are compressed, and it's less work on the client to get the class/clj files out of the archives, but for a typical use case you're not loading entire jars, you're more likely loading a few namespaces each from a dozen of jars, so it would be a lot of data you're sending that's not really needed. 

It would make more sense to hand the server (app process) a url to a jar, or even a set of maven coordinates, and let the server figure out resolving, caching, etc. It would mean a runtime dependency from nrepl on tools.deps, but I think it's the most sensible option. 

I think the side loading design came to be from an assumption that a client like cider would bundle whatever namespaces it needs to side load (say inside a melpa package) cause that's how unrepl works, but unless those are dependency free you're still dealing with doing your own resolution, but now from emacs lisp...

**Comment by alexander-yakushev** [comment]
I mostly agree with you except for one thing – giving nREPL an URL to download. For nREPL sideloading to have any value proposition over `add-lib`, it has to accept real jars/classes from the client. I've worked with many projects that had nREPL server for debugging but no access to Maven or private Artifactory once they are deployed (because it's an additional security risk). Real JAR sideloading would shine in a scenario like this where `add-lib` would fail.

But still, I guess we should wait and see how useful and used `add-lib` turns out before making any decisions about this.

**Comment by bbatsov** [comment]
Closed by #335.
