### ISSUE TITLE
Supplementary pages on nrepl.org are outdated

### ISSUE THREAD

**Issue by alexander-yakushev** [nrepl/nrepl#337]
I've did a doc sweep recently but some pages still feel quite outdated to me.
- https://nrepl.org/nrepl/extensions.html#deprecated – is this section useful? Some of the projects there haven't been updated for 11 years. There is also a list to nREPL github wiki that doesn't feel updated anymore.
- https://nrepl.org/nrepl/beyond_clojure.html – the list can probably be trimmed from unfinished projects or stale abandonware.
- https://nrepl.org/nrepl/troubleshooting.html – mentions of nREPL 0.4.0+ can be removed, I think.
- https://nrepl.org/nrepl/about/team.html – looks outdated, most folks on the list are no longer active here (well, nobody but you, @bbatsov ❤️)
- https://nrepl.org/nrepl/about/support.html – are freenode and discord channels still alive?

**Comment by bbatsov** [comment]
> https://nrepl.org/nrepl/extensions.html#deprecated – is this section useful? Some of the projects there haven't been updated for 11 years. There is also a list to nREPL github wiki that doesn't feel updated anymore.

Yeah, that's not particularly useful today, as the original packages are mostly forgotten by now.

> https://nrepl.org/nrepl/beyond_clojure.html – the list can probably be trimmed from unfinished projects or stale abandonware.

I tried to list everything here with the hope that most people would understand the potential of the protocol, but it's true many of them never got to an usable state. Perhaps we can just split them in two categories - something like production ready vs experimental or whatever. 

> https://nrepl.org/nrepl/troubleshooting.html – mentions of nREPL 0.4.0+ can be removed, I think.

Yeah, that's true. Haven't seen such issues posted in years now. 

> https://nrepl.org/nrepl/about/team.html – looks outdated, most folks on the list are no longer active here (well, nobody but you, @bbatsov ❤️)

Yep. We should move some people to Alumni and add you and @cichli to the active maintainers. 

> https://nrepl.org/nrepl/about/support.html – are freenode and discord channels still alive?

I've mostly stopped using both, so I guess not. We can leave only Slack here.

**Comment by alexander-yakushev** [comment]
Fixed by #338.
