### ISSUE TITLE
Convert docs to AsciiDoc and publish directly to nrepl.org

### ISSUE THREAD

**Issue by bbatsov** [nrepl/nREPL#47]
This is a continuation of https://github.com/cljdoc/cljdoc/issues/95

@SevereOverfl0w "volunteered" to convert the current manual to AsciiDoc. 😄

**Comment by bbatsov** [comment]
Here's the empty repo intended to be used for publishing the site to GH pages https://github.com/nrepl/nREPL.org.

**Comment by SevereOverfl0w** [comment]
I'll get started this weekend, I'll take my keyboard home :smile:

**Comment by bbatsov** [comment]
Fantastic! 🙇
