### ISSUE TITLE
Triage/fix all "legacy" issues from tools.nrepl

### ISSUE THREAD

**Issue by cemerick** [nrepl/nrepl#5]
There are a number of issues reported in the [tools.nrepl JIRA](https://dev.clojure.org/jira/browse/NREPL) that have languished.

Triage them, create new issues for each, and fix here (clean-room impls of any fixes, no patch/diff files from the JIRA to be used!).

This will form the basis of a `1.0.0` release.

**Comment by bbatsov** [comment]
I think we can close this one. To my knowledge all old issues were triaged already. We've fixed those which seemed high priority and we'll tackle the rest down the road.
