### ISSUE TITLE
Test transports-fail-on-disconnects fails during test-all

### ISSUE THREAD

**Issue by benjaminran** [nrepl/nrepl#50]
## Expected behavior
All tests in `lein test-all` should pass.

## Actual behavior

Test `transports-fail-on-disconnects` fails on clojure v1.8 and v1.9 with message:
```
expected: (thrown? SocketException (transport/send transport {"op" "eval", "code" "(+ 5 1)"}))
  actual: nil
```

Full test-all output at https://gist.github.com/benjaminran/c2880f10fc2dad5378b01f7a64a72e57.

**Note:** the test doesn't fail when I run it directly:
```
bnran at dca90496b22a in ~/dev/clj/nREPL on master*
$ lein with-profile base,system,user,provided,dev,1.8 test :only nrepl.core-test/transports-fail-on-disconnects

lein test nrepl.core-test

Ran 1 tests containing 3 assertions.
0 failures, 0 errors.
bnran at dca90496b22a in ~/dev/clj/nREPL on master*
$ lein with-profile base,system,user,provided,dev,1.9 test :only nrepl.core-test/transports-fail-on-disconnects

lein test nrepl.core-test

Ran 1 tests containing 3 assertions.
0 failures, 0 errors.
```

Why does the test fail during test-all but not when run directly? Am I missing something?

## Steps to reproduce the problem
Run `lein test-all`.

### Clojure version
1.8 and 1.9

### Java version

```
bnran at dca90496b22a in ~/dev/clj/nREPL on master*
$ lein --version
Leiningen 2.8.1 on Java 1.8.0_181 Java HotSpot(TM) 64-Bit Server VM
bnran at dca90496b22a in ~/dev/clj/nREPL on master*
$ java -version
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)
```

### Operating system

macOS Sierra 10.12.6 (16G1510)

**Comment by bbatsov** [comment]
Yeah, there's some flakiness in the tests unfortunately. Haven't had time to debug it, so some help with this will be appreciated.

**Comment by pfeodrippe** [comment]
I think we could close this as well
