### ISSUE TITLE
Implement an EDN transport

### ISSUE THREAD

**Issue by bbatsov** [nrepl/nrepl#60]
Having an EDN transport would simplify the lives of people using Clojure/ClojureScript/Java clients for nREPL. It should be pretty easy to create a transport based on the default bencode transport that simply uses EDN instead of bencode. Here's the implementation of the `bencode` transport as a reference:

```clj
(defn bencode
  "Returns a Transport implementation that serializes messages
   over the given Socket or InputStream/OutputStream using bencode."
  ([^Socket s] (bencode s s s))
  ([in out & [^Socket s]]
   (let [in (PushbackInputStream. (io/input-stream in))
         out (io/output-stream out)]
     (fn-transport
      #(let [payload (rethrow-on-disconnection s (bencode/read-bencode in))
             unencoded (<bytes (payload "-unencoded"))
             to-decode (apply dissoc payload "-unencoded" unencoded)]
         (merge (dissoc payload "-unencoded")
                (when unencoded {"-unencoded" unencoded})
                (<bytes to-decode)))
      #(rethrow-on-disconnection s
                                 (locking out
                                   (doto out
                                     (bencode/write-bencode %)
                                     .flush)))
      (fn []
        (if s
          (.close s)
          (do
            (.close in)
            (.close out))))))))
```

The best thing about this transport is that it requires no extra deps, so it can be easily bundled with nREPL itself.

**Comment by dotemacs** [comment]
Let me nudge this along...

Since `bencode` is used, it needs to:
1. read the input
1. decode the input so that it can be used

With EDN it would be something along these lines instead:

```clojure
;; require EDN: [clojure.edn :as cljedn]

(defn edn
  "Returns a Transport implementation that serializes messages
   over the given Socket or InputStream/OutputStream using EDN."
  ([^Socket s] (edn s s s))
  ([in out & [^Socket s]]
   (let [in (PushbackInputStream. (io/input-stream in))
         out (io/writer out)]
     (fn-transport
      #(cljedn/read in)
      #(rethrow-on-disconnection s
                                 (locking out
                                   (doto out
                                     (.write %)
                                     .flush)))
      (fn []
        (if s
          (.close s)
          (do
            (.close in)
            (.close out))))))))
```

Am I going in the right direction here?

**Comment by bbatsov** [comment]
Yeah, seems to me that you're moving in the right direction. The situation with EDN is much simpler because there's nothing really to encode/decode. 

> Since bencode is used, it needs to:

I think I'm missing something. Bencode won't be used at all in an EDN transport.

**Comment by dotemacs** [comment]
I made it into a commit [here](https://github.com/dotemacs/nrepl/commit/6c7f88037da6d932ec45ad487b5d7c7957df9e5d). I'll look at what else needs to be added for this to become a proper pull request.

**Comment by bbatsov** [comment]
Looking forward to it!

**Comment by bbatsov** [comment]
Btw, you can test the result like this:

```
(with-open [conn (nrepl/url-connect "edn://localhost:8000/repl")]
    (-> (nrepl/client conn 1000)
        (nrepl/message {:op "eval" :code "(+ 2 3)"})
        nrepl/response-values))
```

That assumes you've named this protocol edn like this:

```
(.addMethod nrepl/url-connect "edn" #'edn)
```

Maybe a name with `nrepl+end` wold be better. I'll leave to you to figure out those details.

**Comment by dotemacs** [comment]
Thanks for the nudge...

**Comment by bbatsov** [comment]
Any time! 😉

**Comment by dotemacs** [comment]
I think that I've done it, but there is a failing test...

The change is [here](https://github.com/dotemacs/nrepl/commit/7df618b68f15bc7766836558526d80724ec9a810)

Just dealing with this test failure:

```
lein test :only nrepl.core-test/transports-fail-on-disconnects

FAIL in (transports-fail-on-disconnects) (core_test.clj:409)
Ensure that transports fail ASAP when the server they're connected to goes down.
expected: (thrown?
           SocketException
           (transport/send transport {"op" "eval", "code" "(+ 5 1)"}))
  actual: nil
```

**Comment by dotemacs** [comment]
Solved the failing test issue, it was just the way I required things.

I'll open a PR to move the discussion there.

**Comment by bbatsov** [comment]
We're now actively looking for a new volunteer to tackle this.

**Comment by mikepjb** [comment]
I'm not exactly volunteering (yet) but exploring how to do this:

I can get the tests to pass without any changes to the codebase using `make test` (great!)

When introducing a new transport implemented similar to dotemacs' pull request, the first test that fails is explicit-port-argument which I can run for both transports in the REPL with:
```
nrepl.cmdline-test> (server-cmdline-fixture explicit-port-argument)
{:server-socket
 #object[java.net.ServerSocket 0x68c0c1d0 "ServerSocket[addr=/127.0.0.1,localport=45927]"],
 :port 45927,
 :open-transports
 #<Atom@54bf702: 
   #{#object[nrepl.transport.FnTransport 0x267bd66e "nrepl.transport.FnTransport@267bd66e"]}>,
 :transport #'nrepl.transport/bencode,
 :greeting nil,
 :handler
 #object[nrepl.ack$handle_ack$fn__1803 0x5948166e "nrepl.ack$handle_ack$fn__1803@5948166e"]}
{:server-socket
 #object[java.net.ServerSocket 0x64af0d32 "ServerSocket[addr=/127.0.0.1,localport=45253]"],
 :port 45253,
 :open-transports #<Atom@6932326f: #{}>,
 :transport #'nrepl.transport/nrepl+edn,
 :greeting nil,
 :handler
 #object[nrepl.ack$handle_ack$fn__1803 0x7bedce66 "nrepl.ack$handle_ack$fn__1803@7bedce66"]}

FAIL in (explicit-port-argument) (cmdline_test.clj:164)
nrepl+edn transport
```

I've included a `(clojure.pprint/pprint *server*)` in the test to learn a bit more - it looks as though there are no open transports for the nrepl+edn but I have no idea why.

Can anyone offer some guidance on this?
