### ISSUE TITLE
Eliminate illegal access warnings

### ISSUE THREAD

**Issue by bbatsov** [nrepl/nrepl#68]
When we start the server today on JDK 9+ we get:

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by nrepl.middleware.interruptible_eval$set_line_BANG_ to field java.io.FilterReader.in
WARNING: Please consider reporting this to the maintainers of nrepl.middleware.interruptible_eval$set_line_BANG_
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```
There we're setting some protected fields, which was never really a great approach, but now it seems this might be blocked down the road. We need to see how we can set the metadata without breaking data encapsulation. Maybe we can get some inspiration from `clojure.main`?

@mallt Would like to tackle this? I assume it'd be pretty straight-forward.

**Comment by mallt** [comment]
@bbatsov I'm trying to reproduce the warnings on my machine. When I try to launch nrepl from the master branch with `clj -Sdeps '{:deps {nrepl {:mvn/version "0.5.0-SNAPSHOT"}}}' -m nrepl.cmdline --interactive` with openjdk-10 I don't seem to get any warnings.

For which java and clojure version do you get these warnings? Or should nrepl be started differently to be able to see the warnings?

Thanks!

**Comment by bbatsov** [comment]
Hmmm, I start it in exactly the same manner on OracleJDK 10. Clojure 1.9, but this shouldn't matter. 

I get those warnings absolutely every time. I assume it's something to do with your JVM's configuration.

**Comment by bbatsov** [comment]
This seems related - http://mail.openjdk.java.net/pipermail/jigsaw-dev/2017-May/012673.html

What's the value for you?

**Comment by mallt** [comment]
I tried to explicitly set the option with `clj -J--illegal-access=warn -Sdeps '{:deps {nrepl {:mvn/version "0.5.0-SNAPSHOT"}}}' -m nrepl.cmdline --interactive` but even then no warnings are shown.

**Comment by mallt** [comment]
@bbatsov Nevermind, I noticed the warnings are shown when running `lein test`, so that gives me a starting point. :)
