### ISSUE TITLE
Dependency on tools.logging is incompatible with leiningen pedantic feature

### ISSUE THREAD

**Issue by technomancy** [nrepl/nrepl#89]
When using the latest version of Leiningen from git, a dependency on `nrepl` is injected into the list of dependencies whenever the `:base` profile is used (which is most of the time).

When this happens, `org.clojure/tools.logging` is pulled in as an indirect dependency. Any medium-to-large sized Clojure project already pulls in a different version of that library. Such projects which have the `:pedantic?` feature enabled will abort due to the dependency conflict, with no clear way to resolve the conflict.

We can't have any dependencies in the `:base` profile of Leiningen which themselves have dependencies.

## Expected behavior

You can use `org.clojure/tools.logging` in a project with `:pedantic?` enabled.

## Actual behavior

    Aborting due to :pedantic? :abort

## Steps to reproduce the problem

Run `lein test` on any project which has a dependency on `org.clojure/tools.logging` other than 0.4.1 when `:pedantic?` is turned on.

## Environment & Version information

Leiningen running from git master.

**Comment by bbatsov** [comment]
Done.
